# Code generated by smithy-python-codegen DO NOT EDIT.

from pytest import fail
from smithy_core.aio.utils import async_list
from smithy_http import tuples_to_fields
from smithy_http.aio import HTTPResponse as _smithy_http_aio_HTTPResponse
from smithy_http.aio.interfaces import (
    HTTPRequest,
    HTTPResponse as _smithy_http_aio_interfaces_HTTPResponse,
)
from smithy_http.interfaces import HTTPClientConfiguration, HTTPRequestConfiguration
from smithy_test import deep_equal

from parentprobe.client import Probe
from parentprobe.config import Config
from parentprobe.models import ProbeScopeInput, ProbeScopeOutput, ServiceError


async def test_explicit_namespace_after_response_probe_scope() -> None:
    client = Probe(
        config=Config(
            endpoint_uri="https://example.com",
            transport=ResponseTestHTTPClient(
                status=200,
                headers=[],
                body=b'<a:Response xmlns:a="urn:outer"><a:after>outside</a:after></a:Response>',
            ),
        )
    )

    input_ = ProbeScopeInput()

    try:
        actual = await client.probe_scope(input_)
    except Exception as err:
        fail(f"Expected a valid response, but received: {type(err).__name__}: {err}")
    else:
        expected = ProbeScopeOutput(after="outside")

        assert deep_equal(actual, expected)


class TestHttpServiceError(ServiceError):
    """A test error that subclasses the service-error for protocol tests."""

    def __init__(self, request: HTTPRequest):
        self.request = request


class RequestTestHTTPClient:
    """An asynchronous HTTP client solely for testing purposes."""

    TIMEOUT_EXCEPTIONS = ()
    SUPPORTS_DUPLEX_STREAMING: bool = True

    def __init__(self, *, client_config: HTTPClientConfiguration | None = None):
        self._client_config = client_config

    async def send(
        self,
        request: HTTPRequest,
        *,
        request_config: HTTPRequestConfiguration | None = None,
    ) -> _smithy_http_aio_interfaces_HTTPResponse:
        # Raise the exception with the request object to bypass actual request handling
        raise TestHttpServiceError(request)


class ResponseTestHTTPClient:
    """An asynchronous HTTP client solely for testing purposes."""

    TIMEOUT_EXCEPTIONS = ()
    SUPPORTS_DUPLEX_STREAMING: bool = True

    def __init__(
        self,
        *,
        client_config: HTTPClientConfiguration | None = None,
        status: int = 200,
        headers: list[tuple[str, str]] | None = None,
        body: bytes = b"",
    ):
        self._client_config = client_config
        self.status = status
        self.fields = tuples_to_fields(headers or [])
        self.body = body

    async def send(
        self,
        request: HTTPRequest,
        *,
        request_config: HTTPRequestConfiguration | None = None,
    ) -> _smithy_http_aio_HTTPResponse:
        # Pre-construct the response from the request and return it
        return _smithy_http_aio_HTTPResponse(
            status=self.status, fields=self.fields, body=async_list([self.body])
        )
