# Code generated by smithy-python-codegen DO NOT EDIT.

from dataclasses import dataclass
import logging
from typing import Any, Literal, Self

from smithy_core.deserializers import ShapeDeserializer
from smithy_core.documents import TypeRegistry
from smithy_core.exceptions import ModeledError
from smithy_core.schemas import APIOperation, Schema
from smithy_core.serializers import ShapeSerializer
from smithy_core.shapes import ShapeID

from ._private.schemas import (
    EXCHANGE as _SCHEMA_EXCHANGE,
    EXCHANGE_INPUT as _SCHEMA_EXCHANGE_INPUT,
    EXCHANGE_OUTPUT as _SCHEMA_EXCHANGE_OUTPUT,
    MODELED_FAILURE as _SCHEMA_MODELED_FAILURE,
    NESTED as _SCHEMA_NESTED,
)


logger = logging.getLogger(__name__)


class ServiceError(ModeledError):
    """
    Base error for all errors in the service.

    Some exceptions do not extend from this class, including
    synthetic, implicit, and shared exception types.
    """


@dataclass(kw_only=True)
class Nested:
    """Dataclass for Nested structure."""

    value: str | None = None

    def serialize(self, serializer: ShapeSerializer):
        serializer.write_struct(_SCHEMA_NESTED, self)

    def serialize_members(self, serializer: ShapeSerializer):
        if self.value is not None:
            serializer.write_string(_SCHEMA_NESTED.members["value"], self.value)

    @classmethod
    def deserialize(cls, deserializer: ShapeDeserializer) -> Self:
        return cls(**cls.deserialize_kwargs(deserializer))

    @classmethod
    def deserialize_kwargs(cls, deserializer: ShapeDeserializer) -> dict[str, Any]:
        kwargs: dict[str, Any] = {}

        def _consumer(schema: Schema, de: ShapeDeserializer) -> None:
            match schema.expect_member_index():
                case 0:
                    kwargs["value"] = de.read_string(_SCHEMA_NESTED.members["value"])

                case _:
                    logger.debug("Unexpected member schema: %s", schema)

        deserializer.read_struct(_SCHEMA_NESTED, consumer=_consumer)
        return kwargs


def _serialize_entries(
    serializer: ShapeSerializer, schema: Schema, value: dict[str, Nested]
) -> None:
    with serializer.begin_map(schema, len(value)) as m:
        value_schema = schema.members["value"]
        for k, v in value.items():
            m.entry(k, lambda vs: vs.write_struct(value_schema, v))


def _deserialize_entries(
    deserializer: ShapeDeserializer, schema: Schema
) -> dict[str, Nested]:
    result: dict[str, Nested] = {}
    value_schema = schema.members["value"]

    def _read_value(k: str, d: ShapeDeserializer):
        if d.is_null():
            d.read_null()

        else:
            result[k] = Nested.deserialize(d)

    deserializer.read_map(schema, _read_value)
    return result


def _serialize_items(
    serializer: ShapeSerializer, schema: Schema, value: list[Nested]
) -> None:
    member_schema = schema.members["member"]
    with serializer.begin_list(schema, len(value)) as ls:
        for e in value:
            ls.write_struct(member_schema, e)


def _deserialize_items(deserializer: ShapeDeserializer, schema: Schema) -> list[Nested]:
    result: list[Nested] = []

    def _read_value(d: ShapeDeserializer):
        if d.is_null():
            d.read_null()

        else:
            result.append(Nested.deserialize(d))

    deserializer.read_list(schema, _read_value)
    return result


@dataclass(kw_only=True)
class ExchangeInput:
    """Dataclass for ExchangeInput structure."""

    nested: Nested | None = None

    after: str | None = None

    items: list[Nested] | None = None

    entries: dict[str, Nested] | None = None

    def serialize(self, serializer: ShapeSerializer):
        serializer.write_struct(_SCHEMA_EXCHANGE_INPUT, self)

    def serialize_members(self, serializer: ShapeSerializer):
        if self.nested is not None:
            serializer.write_struct(
                _SCHEMA_EXCHANGE_INPUT.members["nested"], self.nested
            )

        if self.after is not None:
            serializer.write_string(_SCHEMA_EXCHANGE_INPUT.members["after"], self.after)

        if self.items is not None:
            _serialize_items(
                serializer, _SCHEMA_EXCHANGE_INPUT.members["items"], self.items
            )

        if self.entries is not None:
            _serialize_entries(
                serializer, _SCHEMA_EXCHANGE_INPUT.members["entries"], self.entries
            )

    @classmethod
    def deserialize(cls, deserializer: ShapeDeserializer) -> Self:
        return cls(**cls.deserialize_kwargs(deserializer))

    @classmethod
    def deserialize_kwargs(cls, deserializer: ShapeDeserializer) -> dict[str, Any]:
        kwargs: dict[str, Any] = {}

        def _consumer(schema: Schema, de: ShapeDeserializer) -> None:
            match schema.expect_member_index():
                case 0:
                    kwargs["nested"] = Nested.deserialize(de)

                case 1:
                    kwargs["after"] = de.read_string(
                        _SCHEMA_EXCHANGE_INPUT.members["after"]
                    )

                case 2:
                    kwargs["items"] = _deserialize_items(
                        de, _SCHEMA_EXCHANGE_INPUT.members["items"]
                    )

                case 3:
                    kwargs["entries"] = _deserialize_entries(
                        de, _SCHEMA_EXCHANGE_INPUT.members["entries"]
                    )

                case _:
                    logger.debug("Unexpected member schema: %s", schema)

        deserializer.read_struct(_SCHEMA_EXCHANGE_INPUT, consumer=_consumer)
        return kwargs


@dataclass(kw_only=True)
class ExchangeOutput:
    """Dataclass for ExchangeOutput structure."""

    nested: Nested | None = None

    after: str | None = None

    items: list[Nested] | None = None

    entries: dict[str, Nested] | None = None

    def serialize(self, serializer: ShapeSerializer):
        serializer.write_struct(_SCHEMA_EXCHANGE_OUTPUT, self)

    def serialize_members(self, serializer: ShapeSerializer):
        if self.nested is not None:
            serializer.write_struct(
                _SCHEMA_EXCHANGE_OUTPUT.members["nested"], self.nested
            )

        if self.after is not None:
            serializer.write_string(
                _SCHEMA_EXCHANGE_OUTPUT.members["after"], self.after
            )

        if self.items is not None:
            _serialize_items(
                serializer, _SCHEMA_EXCHANGE_OUTPUT.members["items"], self.items
            )

        if self.entries is not None:
            _serialize_entries(
                serializer, _SCHEMA_EXCHANGE_OUTPUT.members["entries"], self.entries
            )

    @classmethod
    def deserialize(cls, deserializer: ShapeDeserializer) -> Self:
        return cls(**cls.deserialize_kwargs(deserializer))

    @classmethod
    def deserialize_kwargs(cls, deserializer: ShapeDeserializer) -> dict[str, Any]:
        kwargs: dict[str, Any] = {}

        def _consumer(schema: Schema, de: ShapeDeserializer) -> None:
            match schema.expect_member_index():
                case 0:
                    kwargs["nested"] = Nested.deserialize(de)

                case 1:
                    kwargs["after"] = de.read_string(
                        _SCHEMA_EXCHANGE_OUTPUT.members["after"]
                    )

                case 2:
                    kwargs["items"] = _deserialize_items(
                        de, _SCHEMA_EXCHANGE_OUTPUT.members["items"]
                    )

                case 3:
                    kwargs["entries"] = _deserialize_entries(
                        de, _SCHEMA_EXCHANGE_OUTPUT.members["entries"]
                    )

                case _:
                    logger.debug("Unexpected member schema: %s", schema)

        deserializer.read_struct(_SCHEMA_EXCHANGE_OUTPUT, consumer=_consumer)
        return kwargs


@dataclass(kw_only=True)
class ModeledFailure(ServiceError):
    """Dataclass for ModeledFailure structure."""

    fault: Literal["client", "server"] | None = "client"

    detail: Nested | None = None

    trace: str | None = None

    def serialize(self, serializer: ShapeSerializer):
        serializer.write_struct(_SCHEMA_MODELED_FAILURE, self)

    def serialize_members(self, serializer: ShapeSerializer):
        if self.message is not None:
            serializer.write_string(
                _SCHEMA_MODELED_FAILURE.members["message"], self.message
            )

        if self.detail is not None:
            serializer.write_struct(
                _SCHEMA_MODELED_FAILURE.members["detail"], self.detail
            )

        if self.trace is not None:
            serializer.write_string(
                _SCHEMA_MODELED_FAILURE.members["trace"], self.trace
            )

    @classmethod
    def deserialize(cls, deserializer: ShapeDeserializer) -> Self:
        return cls(**cls.deserialize_kwargs(deserializer))

    @classmethod
    def deserialize_kwargs(cls, deserializer: ShapeDeserializer) -> dict[str, Any]:
        kwargs: dict[str, Any] = {}

        def _consumer(schema: Schema, de: ShapeDeserializer) -> None:
            match schema.expect_member_index():
                case 0:
                    kwargs["message"] = de.read_string(
                        _SCHEMA_MODELED_FAILURE.members["message"]
                    )

                case 1:
                    kwargs["detail"] = Nested.deserialize(de)

                case 2:
                    kwargs["trace"] = de.read_string(
                        _SCHEMA_MODELED_FAILURE.members["trace"]
                    )

                case _:
                    logger.debug("Unexpected member schema: %s", schema)

        deserializer.read_struct(_SCHEMA_MODELED_FAILURE, consumer=_consumer)
        return kwargs


EXCHANGE = APIOperation(
    input=ExchangeInput,
    output=ExchangeOutput,
    schema=_SCHEMA_EXCHANGE,
    input_schema=_SCHEMA_EXCHANGE_INPUT,
    output_schema=_SCHEMA_EXCHANGE_OUTPUT,
    error_registry=TypeRegistry(
        {ShapeID("cleanroom.restxml#ModeledFailure"): ModeledFailure}
    ),
    effective_auth_schemes=[ShapeID("smithy.api#noAuth")],
    error_schemas=[_SCHEMA_MODELED_FAILURE],
)
