# Code generated by smithy-python-codegen DO NOT EDIT.

from types import MappingProxyType

from smithy_core.prelude import STRING
from smithy_core.schemas import Schema
from smithy_core.shapes import ShapeID, ShapeType
from smithy_core.traits import Trait


DEFAULT_NESTED = Schema.collection(
    id=ShapeID("cleanroom.namespaces#DefaultNested"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.api#xmlNamespace"),
            value=MappingProxyType({"uri": "urn:inner"}),
        )
    ],
    members={"value": {"target": STRING}},
)

DEFAULT_ITEMS = Schema.collection(
    id=ShapeID("cleanroom.namespaces#DefaultItems"),
    shape_type=ShapeType.LIST,
    members={
        "member": {
            "target": DEFAULT_NESTED,
            "traits": [
                Trait.new(
                    id=ShapeID("smithy.api#xmlNamespace"),
                    value=MappingProxyType({"uri": "urn:inner"}),
                )
            ],
        }
    },
)

DEFAULT_SCOPE_INPUT = Schema.collection(
    id=ShapeID("cleanroom.namespaces#DefaultScopeInput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"),
            value="cleanroom.namespaces#DefaultData",
        ),
        Trait.new(id=ShapeID("smithy.api#input")),
    ],
    members={
        "nested": {
            "target": DEFAULT_NESTED,
            "traits": [
                Trait.new(
                    id=ShapeID("smithy.api#xmlNamespace"),
                    value=MappingProxyType({"uri": "urn:inner"}),
                )
            ],
        },
        "after": {"target": STRING},
        "items": {"target": DEFAULT_ITEMS},
    },
)

DEFAULT_SCOPE_OUTPUT = Schema.collection(
    id=ShapeID("cleanroom.namespaces#DefaultScopeOutput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"),
            value="cleanroom.namespaces#DefaultData",
        ),
        Trait.new(id=ShapeID("smithy.api#output")),
    ],
    members={
        "nested": {
            "target": DEFAULT_NESTED,
            "traits": [
                Trait.new(
                    id=ShapeID("smithy.api#xmlNamespace"),
                    value=MappingProxyType({"uri": "urn:inner"}),
                )
            ],
        },
        "after": {"target": STRING},
        "items": {"target": DEFAULT_ITEMS},
    },
)

FAILURE = Schema.collection(
    id=ShapeID("cleanroom.namespaces#Failure"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.test#httpResponseTests"),
            value=(
                MappingProxyType(
                    {
                        "id": "NoWrappingFailure",
                        "protocol": "aws.protocols#restXml",
                        "code": 409,
                        "headers": MappingProxyType({"x-trace": "trace"}),
                        "params": MappingProxyType(
                            {
                                "message": "bad",
                                "detail": MappingProxyType({"value": "inner"}),
                                "trace": "trace",
                            }
                        ),
                        "bodyMediaType": "application/xml",
                        "body": '<p:Error xmlns:p="urn:outer" xmlns:q="urn:inner"><p:Code>Failure</p:Code><p:Message>bad</p:Message><q:detail><q:value>inner</q:value></q:detail></p:Error>\n',
                    }
                ),
            ),
        ),
        Trait.new(id=ShapeID("smithy.api#error"), value="client"),
        Trait.new(id=ShapeID("smithy.api#httpError"), value=409),
    ],
    members={
        "message": {"target": STRING},
        "detail": {
            "target": DEFAULT_NESTED,
            "traits": [
                Trait.new(
                    id=ShapeID("smithy.api#xmlNamespace"),
                    value=MappingProxyType({"uri": "urn:inner"}),
                )
            ],
        },
        "trace": {
            "target": STRING,
            "traits": [Trait.new(id=ShapeID("smithy.api#httpHeader"), value="x-trace")],
        },
    },
)

DEFAULT_SCOPE = Schema(
    id=ShapeID("cleanroom.namespaces#DefaultScope"),
    shape_type=ShapeType.OPERATION,
    traits=[
        Trait.new(
            id=ShapeID("smithy.test#httpRequestTests"),
            value=(
                MappingProxyType(
                    {
                        "id": "DefaultScopeRequest",
                        "protocol": "aws.protocols#restXml",
                        "method": "POST",
                        "uri": "/default",
                        "params": MappingProxyType(
                            {
                                "nested": MappingProxyType({"value": "inner"}),
                                "after": "outer",
                                "items": (
                                    MappingProxyType({"value": "one"}),
                                    MappingProxyType({"value": "two"}),
                                ),
                            }
                        ),
                        "bodyMediaType": "application/xml",
                        "body": '<DefaultData xmlns="urn:outer"><nested xmlns="urn:inner"><value>inner</value></nested><after>outer</after><items><member xmlns="urn:inner"><value>one</value></member><member xmlns="urn:inner"><value>two</value></member></items></DefaultData>\n',
                    }
                ),
            ),
        ),
        Trait.new(
            id=ShapeID("smithy.test#httpResponseTests"),
            value=(
                MappingProxyType(
                    {
                        "id": "DefaultScopeResponse",
                        "protocol": "aws.protocols#restXml",
                        "code": 200,
                        "params": MappingProxyType(
                            {
                                "nested": MappingProxyType({"value": "inner"}),
                                "after": "outer",
                                "items": (
                                    MappingProxyType({"value": "one"}),
                                    MappingProxyType({"value": "two"}),
                                ),
                            }
                        ),
                        "bodyMediaType": "application/xml",
                        "body": '<p:DefaultData xmlns:p="urn:outer" xmlns:q="urn:inner"><q:nested><q:value>inner</q:value></q:nested><p:after>outer</p:after><p:items><q:member><q:value>one</q:value></q:member><q:member><q:value>two</q:value></q:member></p:items></p:DefaultData>\n',
                    }
                ),
            ),
        ),
        Trait.new(
            id=ShapeID("smithy.api#http"),
            value=MappingProxyType({"method": "POST", "uri": "/default", "code": 200}),
        ),
    ],
)

NESTED = Schema.collection(
    id=ShapeID("cleanroom.namespaces#Nested"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.api#xmlNamespace"),
            value=MappingProxyType({"uri": "urn:inner", "prefix": "o"}),
        )
    ],
    members={
        "value": {
            "target": STRING,
            "traits": [Trait.new(id=ShapeID("smithy.api#xmlName"), value="o:value")],
        }
    },
)

ENTRIES = Schema.collection(
    id=ShapeID("cleanroom.namespaces#Entries"),
    shape_type=ShapeType.MAP,
    members={
        "key": {"target": STRING},
        "value": {
            "target": NESTED,
            "traits": [
                Trait.new(id=ShapeID("smithy.api#xmlName"), value="o:value"),
                Trait.new(
                    id=ShapeID("smithy.api#xmlNamespace"),
                    value=MappingProxyType({"uri": "urn:inner", "prefix": "o"}),
                ),
            ],
        },
    },
)

ITEMS = Schema.collection(
    id=ShapeID("cleanroom.namespaces#Items"),
    shape_type=ShapeType.LIST,
    members={
        "member": {
            "target": NESTED,
            "traits": [
                Trait.new(
                    id=ShapeID("smithy.api#xmlNamespace"),
                    value=MappingProxyType({"uri": "urn:inner", "prefix": "o"}),
                )
            ],
        }
    },
)

QUALIFIED_INPUT = Schema.collection(
    id=ShapeID("cleanroom.namespaces#QualifiedInput"),
    traits=[
        Trait.new(id=ShapeID("smithy.api#xmlName"), value="o:Request"),
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"),
            value="cleanroom.namespaces#QualifiedData",
        ),
        Trait.new(id=ShapeID("smithy.api#input")),
        Trait.new(
            id=ShapeID("smithy.api#xmlNamespace"),
            value=MappingProxyType({"uri": "urn:outer", "prefix": "o"}),
        ),
    ],
    members={
        "nested": {
            "target": NESTED,
            "traits": [
                Trait.new(id=ShapeID("smithy.api#xmlName"), value="o:nested"),
                Trait.new(
                    id=ShapeID("smithy.api#xmlNamespace"),
                    value=MappingProxyType({"uri": "urn:inner", "prefix": "o"}),
                ),
            ],
        },
        "after": {
            "target": STRING,
            "traits": [Trait.new(id=ShapeID("smithy.api#xmlName"), value="o:after")],
        },
        "items": {
            "target": ITEMS,
            "traits": [
                Trait.new(id=ShapeID("smithy.api#xmlName"), value="o:item"),
                Trait.new(id=ShapeID("smithy.api#xmlFlattened")),
            ],
        },
        "entries": {
            "target": ENTRIES,
            "traits": [
                Trait.new(id=ShapeID("smithy.api#xmlName"), value="o:entry"),
                Trait.new(id=ShapeID("smithy.api#xmlFlattened")),
            ],
        },
        "attr": {
            "target": STRING,
            "traits": [Trait.new(id=ShapeID("smithy.api#xmlAttribute"))],
        },
    },
)

QUALIFIED_OUTPUT = Schema.collection(
    id=ShapeID("cleanroom.namespaces#QualifiedOutput"),
    traits=[
        Trait.new(id=ShapeID("smithy.api#xmlName"), value="o:Request"),
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"),
            value="cleanroom.namespaces#QualifiedData",
        ),
        Trait.new(id=ShapeID("smithy.api#output")),
        Trait.new(
            id=ShapeID("smithy.api#xmlNamespace"),
            value=MappingProxyType({"uri": "urn:outer", "prefix": "o"}),
        ),
    ],
    members={
        "nested": {
            "target": NESTED,
            "traits": [
                Trait.new(id=ShapeID("smithy.api#xmlName"), value="o:nested"),
                Trait.new(
                    id=ShapeID("smithy.api#xmlNamespace"),
                    value=MappingProxyType({"uri": "urn:inner", "prefix": "o"}),
                ),
            ],
        },
        "after": {
            "target": STRING,
            "traits": [Trait.new(id=ShapeID("smithy.api#xmlName"), value="o:after")],
        },
        "items": {
            "target": ITEMS,
            "traits": [
                Trait.new(id=ShapeID("smithy.api#xmlName"), value="o:item"),
                Trait.new(id=ShapeID("smithy.api#xmlFlattened")),
            ],
        },
        "entries": {
            "target": ENTRIES,
            "traits": [
                Trait.new(id=ShapeID("smithy.api#xmlName"), value="o:entry"),
                Trait.new(id=ShapeID("smithy.api#xmlFlattened")),
            ],
        },
        "attr": {
            "target": STRING,
            "traits": [Trait.new(id=ShapeID("smithy.api#xmlAttribute"))],
        },
    },
)

QUALIFIED = Schema(
    id=ShapeID("cleanroom.namespaces#Qualified"),
    shape_type=ShapeType.OPERATION,
    traits=[
        Trait.new(
            id=ShapeID("smithy.test#httpRequestTests"),
            value=(
                MappingProxyType(
                    {
                        "id": "QualifiedScopeRequest",
                        "protocol": "aws.protocols#restXml",
                        "method": "POST",
                        "uri": "/qualified",
                        "params": MappingProxyType(
                            {
                                "nested": MappingProxyType({"value": "inner"}),
                                "after": "outer",
                                "items": (
                                    MappingProxyType({"value": "one"}),
                                    MappingProxyType({"value": "two"}),
                                ),
                                "entries": MappingProxyType(
                                    {
                                        "a": MappingProxyType({"value": "first"}),
                                        "b": MappingProxyType({"value": "second"}),
                                    }
                                ),
                                "attr": '<&"雪',
                            }
                        ),
                        "bodyMediaType": "application/xml",
                        "body": '<o:Request xmlns="urn:outer" xmlns:o="urn:outer" attr="&lt;&amp;&quot;雪">\n  <o:nested xmlns:o="urn:inner"><o:value>inner</o:value></o:nested>\n  <o:after>outer</o:after>\n  <o:item xmlns:o="urn:inner"><o:value>one</o:value></o:item>\n  <o:item xmlns:o="urn:inner"><o:value>two</o:value></o:item>\n  <o:entry><key>a</key><o:value xmlns:o="urn:inner"><o:value>first</o:value></o:value></o:entry>\n  <o:entry><key>b</key><o:value xmlns:o="urn:inner"><o:value>second</o:value></o:value></o:entry>\n</o:Request>\n',
                    }
                ),
            ),
        ),
        Trait.new(
            id=ShapeID("smithy.test#httpResponseTests"),
            value=(
                MappingProxyType(
                    {
                        "id": "QualifiedScopeResponse",
                        "protocol": "aws.protocols#restXml",
                        "code": 200,
                        "params": MappingProxyType(
                            {
                                "nested": MappingProxyType({"value": "inner"}),
                                "after": "outer",
                                "items": (
                                    MappingProxyType({"value": "one"}),
                                    MappingProxyType({"value": "two"}),
                                ),
                                "entries": MappingProxyType(
                                    {
                                        "a": MappingProxyType({"value": "first"}),
                                        "b": MappingProxyType({"value": "second"}),
                                    }
                                ),
                                "attr": '<&"雪',
                            }
                        ),
                        "bodyMediaType": "application/xml",
                        "body": '<p:Request xmlns="urn:outer" xmlns:p="urn:outer" xmlns:q="urn:inner" attr="&lt;&amp;&quot;雪">\n  <q:nested><q:value>inner</q:value></q:nested><p:after>outer</p:after>\n  <q:item><q:value>one</q:value></q:item><q:item><q:value>two</q:value></q:item>\n  <p:entry><key>a</key><q:value><q:value>first</q:value></q:value></p:entry>\n  <p:entry><key>b</key><q:value><q:value>second</q:value></q:value></p:entry>\n</p:Request>\n',
                    }
                ),
            ),
        ),
        Trait.new(
            id=ShapeID("smithy.api#http"),
            value=MappingProxyType(
                {"method": "POST", "uri": "/qualified", "code": 200}
            ),
        ),
    ],
)

NAMESPACES = Schema(
    id=ShapeID("cleanroom.namespaces#Namespaces"),
    shape_type=ShapeType.SERVICE,
    traits=[
        Trait.new(
            id=ShapeID("aws.protocols#restXml"),
            value=MappingProxyType({"noErrorWrapping": True}),
        ),
        Trait.new(
            id=ShapeID("smithy.api#xmlNamespace"),
            value=MappingProxyType({"uri": "urn:outer"}),
        ),
    ],
)
