# Code generated by smithy-python-codegen DO NOT EDIT.

from dataclasses import dataclass
import logging
from typing import Any, Literal, Self, Union

from smithy_core.deserializers import ShapeDeserializer
from smithy_core.documents import TypeRegistry
from smithy_core.exceptions import ModeledError, SerializationError
from smithy_core.schemas import APIOperation, Schema
from smithy_core.serializers import ShapeSerializer
from smithy_core.shapes import ShapeID

from ._private.schemas import (
    BINARY as _SCHEMA_BINARY,
    BINARY_INPUT as _SCHEMA_BINARY_INPUT,
    BINARY_OUTPUT as _SCHEMA_BINARY_OUTPUT,
    CHOICE as _SCHEMA_CHOICE,
    EXCHANGE as _SCHEMA_EXCHANGE,
    EXCHANGE_INPUT as _SCHEMA_EXCHANGE_INPUT,
    EXCHANGE_OUTPUT as _SCHEMA_EXCHANGE_OUTPUT,
    FAILURE as _SCHEMA_FAILURE,
    PAYLOAD as _SCHEMA_PAYLOAD,
    PAYLOAD_INPUT as _SCHEMA_PAYLOAD_INPUT,
    PAYLOAD_OUTPUT as _SCHEMA_PAYLOAD_OUTPUT,
    ROOT as _SCHEMA_ROOT,
    TEXT as _SCHEMA_TEXT,
    TEXT_INPUT as _SCHEMA_TEXT_INPUT,
    TEXT_OUTPUT as _SCHEMA_TEXT_OUTPUT,
)


logger = logging.getLogger(__name__)


class ServiceError(ModeledError):
    """
    Base error for all errors in the service.

    Some exceptions do not extend from this class, including
    synthetic, implicit, and shared exception types.
    """


@dataclass(kw_only=True)
class BinaryInput:
    """Dataclass for BinaryInput structure."""

    value: bytes | None = None

    def serialize(self, serializer: ShapeSerializer):
        serializer.write_struct(_SCHEMA_BINARY_INPUT, self)

    def serialize_members(self, serializer: ShapeSerializer):
        if self.value is not None:
            serializer.write_blob(_SCHEMA_BINARY_INPUT.members["value"], self.value)

    @classmethod
    def deserialize(cls, deserializer: ShapeDeserializer) -> Self:
        return cls(**cls.deserialize_kwargs(deserializer))

    @classmethod
    def deserialize_kwargs(cls, deserializer: ShapeDeserializer) -> dict[str, Any]:
        kwargs: dict[str, Any] = {}

        def _consumer(schema: Schema, de: ShapeDeserializer) -> None:
            match schema.expect_member_index():
                case 0:
                    kwargs["value"] = de.read_blob(
                        _SCHEMA_BINARY_INPUT.members["value"]
                    )

                case _:
                    logger.debug("Unexpected member schema: %s", schema)

        deserializer.read_struct(_SCHEMA_BINARY_INPUT, consumer=_consumer)
        return kwargs


@dataclass(kw_only=True)
class BinaryOutput:
    """Dataclass for BinaryOutput structure."""

    value: bytes | None = None

    def serialize(self, serializer: ShapeSerializer):
        serializer.write_struct(_SCHEMA_BINARY_OUTPUT, self)

    def serialize_members(self, serializer: ShapeSerializer):
        if self.value is not None:
            serializer.write_blob(_SCHEMA_BINARY_OUTPUT.members["value"], self.value)

    @classmethod
    def deserialize(cls, deserializer: ShapeDeserializer) -> Self:
        return cls(**cls.deserialize_kwargs(deserializer))

    @classmethod
    def deserialize_kwargs(cls, deserializer: ShapeDeserializer) -> dict[str, Any]:
        kwargs: dict[str, Any] = {}

        def _consumer(schema: Schema, de: ShapeDeserializer) -> None:
            match schema.expect_member_index():
                case 0:
                    kwargs["value"] = de.read_blob(
                        _SCHEMA_BINARY_OUTPUT.members["value"]
                    )

                case _:
                    logger.debug("Unexpected member schema: %s", schema)

        deserializer.read_struct(_SCHEMA_BINARY_OUTPUT, consumer=_consumer)
        return kwargs


BINARY = APIOperation(
    input=BinaryInput,
    output=BinaryOutput,
    schema=_SCHEMA_BINARY,
    input_schema=_SCHEMA_BINARY_INPUT,
    output_schema=_SCHEMA_BINARY_OUTPUT,
    error_registry=TypeRegistry({}),
    effective_auth_schemes=[ShapeID("smithy.api#noAuth")],
    error_schemas=[],
)


@dataclass(kw_only=True)
class Root:
    """Dataclass for Root structure."""

    value: str | None = None

    def serialize(self, serializer: ShapeSerializer):
        serializer.write_struct(_SCHEMA_ROOT, self)

    def serialize_members(self, serializer: ShapeSerializer):
        if self.value is not None:
            serializer.write_string(_SCHEMA_ROOT.members["value"], self.value)

    @classmethod
    def deserialize(cls, deserializer: ShapeDeserializer) -> Self:
        return cls(**cls.deserialize_kwargs(deserializer))

    @classmethod
    def deserialize_kwargs(cls, deserializer: ShapeDeserializer) -> dict[str, Any]:
        kwargs: dict[str, Any] = {}

        def _consumer(schema: Schema, de: ShapeDeserializer) -> None:
            match schema.expect_member_index():
                case 0:
                    kwargs["value"] = de.read_string(_SCHEMA_ROOT.members["value"])

                case _:
                    logger.debug("Unexpected member schema: %s", schema)

        deserializer.read_struct(_SCHEMA_ROOT, consumer=_consumer)
        return kwargs


@dataclass
class ChoiceText:
    value: str

    def serialize(self, serializer: ShapeSerializer):
        serializer.write_struct(_SCHEMA_CHOICE, self)

    def serialize_members(self, serializer: ShapeSerializer):
        serializer.write_string(_SCHEMA_CHOICE.members["text"], self.value)

    @classmethod
    def deserialize(cls, deserializer: ShapeDeserializer) -> Self:
        return cls(value=deserializer.read_string(_SCHEMA_CHOICE.members["text"]))


@dataclass
class ChoiceNested:
    value: Root

    def serialize(self, serializer: ShapeSerializer):
        serializer.write_struct(_SCHEMA_CHOICE, self)

    def serialize_members(self, serializer: ShapeSerializer):
        serializer.write_struct(_SCHEMA_CHOICE.members["nested"], self.value)

    @classmethod
    def deserialize(cls, deserializer: ShapeDeserializer) -> Self:
        return cls(value=Root.deserialize(deserializer))


@dataclass
class ChoiceUnknown:
    """
    Represents an unknown variant.

    If you receive this value, you will need to update your library to receive the
    parsed value.

    This value may not be deliberately sent.
    """

    tag: str

    def serialize(self, serializer: ShapeSerializer):
        raise SerializationError("Unknown union variants may not be serialized.")

    def serialize_members(self, serializer: ShapeSerializer):
        raise SerializationError("Unknown union variants may not be serialized.")

    @classmethod
    def deserialize(cls, deserializer: ShapeDeserializer) -> Self:
        raise NotImplementedError()


Choice = Union[ChoiceText | ChoiceNested | ChoiceUnknown]


class _ChoiceDeserializer:
    _result: Choice | None = None

    def deserialize(self, deserializer: ShapeDeserializer) -> Choice:
        self._result = None
        deserializer.read_struct(_SCHEMA_CHOICE, self._consumer)

        if self._result is None:
            raise SerializationError(
                "Unions must have exactly one value, but found none."
            )

        return self._result

    def _consumer(self, schema: Schema, de: ShapeDeserializer) -> None:
        match schema.expect_member_index():
            case 0:
                self._set_result(ChoiceText.deserialize(de))

            case 1:
                self._set_result(ChoiceNested.deserialize(de))

            case _:
                self._set_result(ChoiceUnknown(tag=schema.expect_member_name()))

    def _set_result(self, value: Choice) -> None:
        if self._result is not None:
            raise SerializationError(
                "Unions must have exactly one value, but found more than one."
            )
        self._result = value


def _serialize_entries(
    serializer: ShapeSerializer, schema: Schema, value: dict[str, str]
) -> None:
    with serializer.begin_map(schema, len(value)) as m:
        value_schema = schema.members["value"]
        for k, v in value.items():
            m.entry(k, lambda vs: vs.write_string(value_schema, v))


def _deserialize_entries(
    deserializer: ShapeDeserializer, schema: Schema
) -> dict[str, str]:
    result: dict[str, str] = {}
    value_schema = schema.members["value"]

    def _read_value(k: str, d: ShapeDeserializer):
        if d.is_null():
            d.read_null()

        else:
            result[k] = d.read_string(value_schema)

    deserializer.read_map(schema, _read_value)
    return result


def _serialize_items(
    serializer: ShapeSerializer, schema: Schema, value: list[Root]
) -> None:
    member_schema = schema.members["member"]
    with serializer.begin_list(schema, len(value)) as ls:
        for e in value:
            ls.write_struct(member_schema, e)


def _deserialize_items(deserializer: ShapeDeserializer, schema: Schema) -> list[Root]:
    result: list[Root] = []

    def _read_value(d: ShapeDeserializer):
        if d.is_null():
            d.read_null()

        else:
            result.append(Root.deserialize(d))

    deserializer.read_list(schema, _read_value)
    return result


@dataclass(kw_only=True)
class ExchangeInput:
    """Dataclass for ExchangeInput structure."""

    nested: Root | None = None

    items: list[Root] | None = None

    entries: dict[str, str] | None = None

    choice: Choice | None = None

    attribute: str | None = None

    def serialize(self, serializer: ShapeSerializer):
        serializer.write_struct(_SCHEMA_EXCHANGE_INPUT, self)

    def serialize_members(self, serializer: ShapeSerializer):
        if self.nested is not None:
            serializer.write_struct(
                _SCHEMA_EXCHANGE_INPUT.members["nested"], self.nested
            )

        if self.items is not None:
            _serialize_items(
                serializer, _SCHEMA_EXCHANGE_INPUT.members["items"], self.items
            )

        if self.entries is not None:
            _serialize_entries(
                serializer, _SCHEMA_EXCHANGE_INPUT.members["entries"], self.entries
            )

        if self.choice is not None:
            serializer.write_struct(
                _SCHEMA_EXCHANGE_INPUT.members["choice"], self.choice
            )

        if self.attribute is not None:
            serializer.write_string(
                _SCHEMA_EXCHANGE_INPUT.members["attribute"], self.attribute
            )

    @classmethod
    def deserialize(cls, deserializer: ShapeDeserializer) -> Self:
        return cls(**cls.deserialize_kwargs(deserializer))

    @classmethod
    def deserialize_kwargs(cls, deserializer: ShapeDeserializer) -> dict[str, Any]:
        kwargs: dict[str, Any] = {}

        def _consumer(schema: Schema, de: ShapeDeserializer) -> None:
            match schema.expect_member_index():
                case 0:
                    kwargs["nested"] = Root.deserialize(de)

                case 1:
                    kwargs["items"] = _deserialize_items(
                        de, _SCHEMA_EXCHANGE_INPUT.members["items"]
                    )

                case 2:
                    kwargs["entries"] = _deserialize_entries(
                        de, _SCHEMA_EXCHANGE_INPUT.members["entries"]
                    )

                case 3:
                    kwargs["choice"] = _ChoiceDeserializer().deserialize(de)

                case 4:
                    kwargs["attribute"] = de.read_string(
                        _SCHEMA_EXCHANGE_INPUT.members["attribute"]
                    )

                case _:
                    logger.debug("Unexpected member schema: %s", schema)

        deserializer.read_struct(_SCHEMA_EXCHANGE_INPUT, consumer=_consumer)
        return kwargs


@dataclass(kw_only=True)
class ExchangeOutput:
    """Dataclass for ExchangeOutput structure."""

    nested: Root | None = None

    items: list[Root] | None = None

    entries: dict[str, str] | None = None

    choice: Choice | None = None

    attribute: str | None = None

    def serialize(self, serializer: ShapeSerializer):
        serializer.write_struct(_SCHEMA_EXCHANGE_OUTPUT, self)

    def serialize_members(self, serializer: ShapeSerializer):
        if self.nested is not None:
            serializer.write_struct(
                _SCHEMA_EXCHANGE_OUTPUT.members["nested"], self.nested
            )

        if self.items is not None:
            _serialize_items(
                serializer, _SCHEMA_EXCHANGE_OUTPUT.members["items"], self.items
            )

        if self.entries is not None:
            _serialize_entries(
                serializer, _SCHEMA_EXCHANGE_OUTPUT.members["entries"], self.entries
            )

        if self.choice is not None:
            serializer.write_struct(
                _SCHEMA_EXCHANGE_OUTPUT.members["choice"], self.choice
            )

        if self.attribute is not None:
            serializer.write_string(
                _SCHEMA_EXCHANGE_OUTPUT.members["attribute"], self.attribute
            )

    @classmethod
    def deserialize(cls, deserializer: ShapeDeserializer) -> Self:
        return cls(**cls.deserialize_kwargs(deserializer))

    @classmethod
    def deserialize_kwargs(cls, deserializer: ShapeDeserializer) -> dict[str, Any]:
        kwargs: dict[str, Any] = {}

        def _consumer(schema: Schema, de: ShapeDeserializer) -> None:
            match schema.expect_member_index():
                case 0:
                    kwargs["nested"] = Root.deserialize(de)

                case 1:
                    kwargs["items"] = _deserialize_items(
                        de, _SCHEMA_EXCHANGE_OUTPUT.members["items"]
                    )

                case 2:
                    kwargs["entries"] = _deserialize_entries(
                        de, _SCHEMA_EXCHANGE_OUTPUT.members["entries"]
                    )

                case 3:
                    kwargs["choice"] = _ChoiceDeserializer().deserialize(de)

                case 4:
                    kwargs["attribute"] = de.read_string(
                        _SCHEMA_EXCHANGE_OUTPUT.members["attribute"]
                    )

                case _:
                    logger.debug("Unexpected member schema: %s", schema)

        deserializer.read_struct(_SCHEMA_EXCHANGE_OUTPUT, consumer=_consumer)
        return kwargs


@dataclass(kw_only=True)
class Failure(ServiceError):
    """Dataclass for Failure structure."""

    fault: Literal["client", "server"] | None = "client"

    detail: Root | None = None

    trace: str | None = None

    def serialize(self, serializer: ShapeSerializer):
        serializer.write_struct(_SCHEMA_FAILURE, self)

    def serialize_members(self, serializer: ShapeSerializer):
        if self.message is not None:
            serializer.write_string(_SCHEMA_FAILURE.members["message"], self.message)

        if self.detail is not None:
            serializer.write_struct(_SCHEMA_FAILURE.members["detail"], self.detail)

        if self.trace is not None:
            serializer.write_string(_SCHEMA_FAILURE.members["trace"], self.trace)

    @classmethod
    def deserialize(cls, deserializer: ShapeDeserializer) -> Self:
        return cls(**cls.deserialize_kwargs(deserializer))

    @classmethod
    def deserialize_kwargs(cls, deserializer: ShapeDeserializer) -> dict[str, Any]:
        kwargs: dict[str, Any] = {}

        def _consumer(schema: Schema, de: ShapeDeserializer) -> None:
            match schema.expect_member_index():
                case 0:
                    kwargs["message"] = de.read_string(
                        _SCHEMA_FAILURE.members["message"]
                    )

                case 1:
                    kwargs["detail"] = Root.deserialize(de)

                case 2:
                    kwargs["trace"] = de.read_string(_SCHEMA_FAILURE.members["trace"])

                case _:
                    logger.debug("Unexpected member schema: %s", schema)

        deserializer.read_struct(_SCHEMA_FAILURE, consumer=_consumer)
        return kwargs


EXCHANGE = APIOperation(
    input=ExchangeInput,
    output=ExchangeOutput,
    schema=_SCHEMA_EXCHANGE,
    input_schema=_SCHEMA_EXCHANGE_INPUT,
    output_schema=_SCHEMA_EXCHANGE_OUTPUT,
    error_registry=TypeRegistry({ShapeID("cleanroom.regressions#Failure"): Failure}),
    effective_auth_schemes=[ShapeID("smithy.api#noAuth")],
    error_schemas=[_SCHEMA_FAILURE],
)


@dataclass(kw_only=True)
class PayloadInput:
    """Dataclass for PayloadInput structure."""

    value: Root | None = None

    def serialize(self, serializer: ShapeSerializer):
        serializer.write_struct(_SCHEMA_PAYLOAD_INPUT, self)

    def serialize_members(self, serializer: ShapeSerializer):
        if self.value is not None:
            serializer.write_struct(_SCHEMA_PAYLOAD_INPUT.members["value"], self.value)

    @classmethod
    def deserialize(cls, deserializer: ShapeDeserializer) -> Self:
        return cls(**cls.deserialize_kwargs(deserializer))

    @classmethod
    def deserialize_kwargs(cls, deserializer: ShapeDeserializer) -> dict[str, Any]:
        kwargs: dict[str, Any] = {}

        def _consumer(schema: Schema, de: ShapeDeserializer) -> None:
            match schema.expect_member_index():
                case 0:
                    kwargs["value"] = Root.deserialize(de)

                case _:
                    logger.debug("Unexpected member schema: %s", schema)

        deserializer.read_struct(_SCHEMA_PAYLOAD_INPUT, consumer=_consumer)
        return kwargs


@dataclass(kw_only=True)
class PayloadOutput:
    """Dataclass for PayloadOutput structure."""

    value: Root | None = None

    def serialize(self, serializer: ShapeSerializer):
        serializer.write_struct(_SCHEMA_PAYLOAD_OUTPUT, self)

    def serialize_members(self, serializer: ShapeSerializer):
        if self.value is not None:
            serializer.write_struct(_SCHEMA_PAYLOAD_OUTPUT.members["value"], self.value)

    @classmethod
    def deserialize(cls, deserializer: ShapeDeserializer) -> Self:
        return cls(**cls.deserialize_kwargs(deserializer))

    @classmethod
    def deserialize_kwargs(cls, deserializer: ShapeDeserializer) -> dict[str, Any]:
        kwargs: dict[str, Any] = {}

        def _consumer(schema: Schema, de: ShapeDeserializer) -> None:
            match schema.expect_member_index():
                case 0:
                    kwargs["value"] = Root.deserialize(de)

                case _:
                    logger.debug("Unexpected member schema: %s", schema)

        deserializer.read_struct(_SCHEMA_PAYLOAD_OUTPUT, consumer=_consumer)
        return kwargs


PAYLOAD = APIOperation(
    input=PayloadInput,
    output=PayloadOutput,
    schema=_SCHEMA_PAYLOAD,
    input_schema=_SCHEMA_PAYLOAD_INPUT,
    output_schema=_SCHEMA_PAYLOAD_OUTPUT,
    error_registry=TypeRegistry({}),
    effective_auth_schemes=[ShapeID("smithy.api#noAuth")],
    error_schemas=[],
)


@dataclass(kw_only=True)
class TextInput:
    """Dataclass for TextInput structure."""

    value: str | None = None

    def serialize(self, serializer: ShapeSerializer):
        serializer.write_struct(_SCHEMA_TEXT_INPUT, self)

    def serialize_members(self, serializer: ShapeSerializer):
        if self.value is not None:
            serializer.write_string(_SCHEMA_TEXT_INPUT.members["value"], self.value)

    @classmethod
    def deserialize(cls, deserializer: ShapeDeserializer) -> Self:
        return cls(**cls.deserialize_kwargs(deserializer))

    @classmethod
    def deserialize_kwargs(cls, deserializer: ShapeDeserializer) -> dict[str, Any]:
        kwargs: dict[str, Any] = {}

        def _consumer(schema: Schema, de: ShapeDeserializer) -> None:
            match schema.expect_member_index():
                case 0:
                    kwargs["value"] = de.read_string(
                        _SCHEMA_TEXT_INPUT.members["value"]
                    )

                case _:
                    logger.debug("Unexpected member schema: %s", schema)

        deserializer.read_struct(_SCHEMA_TEXT_INPUT, consumer=_consumer)
        return kwargs


@dataclass(kw_only=True)
class TextOutput:
    """Dataclass for TextOutput structure."""

    value: str | None = None

    def serialize(self, serializer: ShapeSerializer):
        serializer.write_struct(_SCHEMA_TEXT_OUTPUT, self)

    def serialize_members(self, serializer: ShapeSerializer):
        if self.value is not None:
            serializer.write_string(_SCHEMA_TEXT_OUTPUT.members["value"], self.value)

    @classmethod
    def deserialize(cls, deserializer: ShapeDeserializer) -> Self:
        return cls(**cls.deserialize_kwargs(deserializer))

    @classmethod
    def deserialize_kwargs(cls, deserializer: ShapeDeserializer) -> dict[str, Any]:
        kwargs: dict[str, Any] = {}

        def _consumer(schema: Schema, de: ShapeDeserializer) -> None:
            match schema.expect_member_index():
                case 0:
                    kwargs["value"] = de.read_string(
                        _SCHEMA_TEXT_OUTPUT.members["value"]
                    )

                case _:
                    logger.debug("Unexpected member schema: %s", schema)

        deserializer.read_struct(_SCHEMA_TEXT_OUTPUT, consumer=_consumer)
        return kwargs


TEXT = APIOperation(
    input=TextInput,
    output=TextOutput,
    schema=_SCHEMA_TEXT,
    input_schema=_SCHEMA_TEXT_INPUT,
    output_schema=_SCHEMA_TEXT_OUTPUT,
    error_registry=TypeRegistry({}),
    effective_auth_schemes=[ShapeID("smithy.api#noAuth")],
    error_schemas=[],
)
