# Code generated by smithy-python-codegen DO NOT EDIT.

from types import MappingProxyType

from smithy_core.prelude import STRING
from smithy_core.schemas import Schema
from smithy_core.shapes import ShapeID, ShapeType
from smithy_core.traits import Trait


NESTED = Schema.collection(
    id=ShapeID("cleanroom.restxml#Nested"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.api#xmlNamespace"),
            value=MappingProxyType({"uri": "urn:inner", "prefix": "o"}),
        )
    ],
    members={"value": {"target": STRING}},
)

ENTRIES = Schema.collection(
    id=ShapeID("cleanroom.restxml#Entries"),
    shape_type=ShapeType.MAP,
    members={"key": {"target": STRING}, "value": {"target": NESTED}},
)

ITEMS = Schema.collection(
    id=ShapeID("cleanroom.restxml#Items"),
    shape_type=ShapeType.LIST,
    members={"member": {"target": NESTED}},
)

EXCHANGE_INPUT = Schema.collection(
    id=ShapeID("cleanroom.restxml#ExchangeInput"),
    traits=[
        Trait.new(id=ShapeID("smithy.api#xmlName"), value="Request"),
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"),
            value="cleanroom.restxml#Input",
        ),
        Trait.new(id=ShapeID("smithy.api#input")),
    ],
    members={
        "nested": {"target": NESTED},
        "after": {"target": STRING},
        "items": {
            "target": ITEMS,
            "traits": [
                Trait.new(id=ShapeID("smithy.api#xmlName"), value="item"),
                Trait.new(id=ShapeID("smithy.api#xmlFlattened")),
            ],
        },
        "entries": {
            "target": ENTRIES,
            "traits": [
                Trait.new(id=ShapeID("smithy.api#xmlName"), value="entry"),
                Trait.new(id=ShapeID("smithy.api#xmlFlattened")),
            ],
        },
    },
)

EXCHANGE_OUTPUT = Schema.collection(
    id=ShapeID("cleanroom.restxml#ExchangeOutput"),
    traits=[
        Trait.new(id=ShapeID("smithy.api#xmlName"), value="Response"),
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"),
            value="cleanroom.restxml#Output",
        ),
        Trait.new(id=ShapeID("smithy.api#output")),
    ],
    members={
        "nested": {"target": NESTED},
        "after": {"target": STRING},
        "items": {
            "target": ITEMS,
            "traits": [
                Trait.new(id=ShapeID("smithy.api#xmlName"), value="item"),
                Trait.new(id=ShapeID("smithy.api#xmlFlattened")),
            ],
        },
        "entries": {
            "target": ENTRIES,
            "traits": [
                Trait.new(id=ShapeID("smithy.api#xmlName"), value="entry"),
                Trait.new(id=ShapeID("smithy.api#xmlFlattened")),
            ],
        },
    },
)

MODELED_FAILURE = Schema.collection(
    id=ShapeID("cleanroom.restxml#ModeledFailure"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.test#httpResponseTests"),
            value=(
                MappingProxyType(
                    {
                        "id": "FrozenScopeModeledFailure",
                        "protocol": "aws.protocols#restXml",
                        "code": 409,
                        "headers": MappingProxyType({"x-trace": "trace-id"}),
                        "params": MappingProxyType(
                            {
                                "message": "bad",
                                "detail": MappingProxyType({"value": "inner"}),
                                "trace": "trace-id",
                            }
                        ),
                        "bodyMediaType": "application/xml",
                        "body": '<ErrorResponse xmlns:q="urn:outer"><Error>\n  <Code>ModeledFailure</Code><Message>bad</Message>\n  <detail xmlns:r="urn:inner"><value>inner</value></detail>\n</Error></ErrorResponse>\n',
                    }
                ),
            ),
        ),
        Trait.new(id=ShapeID("smithy.api#error"), value="client"),
        Trait.new(id=ShapeID("smithy.api#httpError"), value=409),
    ],
    members={
        "message": {"target": STRING},
        "detail": {"target": NESTED},
        "trace": {
            "target": STRING,
            "traits": [Trait.new(id=ShapeID("smithy.api#httpHeader"), value="x-trace")],
        },
    },
)

EXCHANGE = Schema(
    id=ShapeID("cleanroom.restxml#Exchange"),
    shape_type=ShapeType.OPERATION,
    traits=[
        Trait.new(
            id=ShapeID("smithy.test#httpRequestTests"),
            value=(
                MappingProxyType(
                    {
                        "id": "FrozenScopeRequest",
                        "protocol": "aws.protocols#restXml",
                        "method": "POST",
                        "uri": "/exchange",
                        "params": MappingProxyType(
                            {
                                "nested": MappingProxyType({"value": "inner"}),
                                "after": "outer",
                                "items": (
                                    MappingProxyType({"value": "one"}),
                                    MappingProxyType({"value": "two"}),
                                ),
                                "entries": MappingProxyType(
                                    {
                                        "a": MappingProxyType({"value": "first"}),
                                        "b": MappingProxyType({"value": "second"}),
                                    }
                                ),
                            }
                        ),
                        "bodyMediaType": "application/xml",
                        "body": '<Request xmlns:o="urn:outer">\n  <nested xmlns:o="urn:inner"><value>inner</value></nested>\n  <after>outer</after>\n  <item xmlns:o="urn:inner"><value>one</value></item>\n  <item xmlns:o="urn:inner"><value>two</value></item>\n  <entry><key>a</key><value xmlns:o="urn:inner"><value>first</value></value></entry>\n  <entry><key>b</key><value xmlns:o="urn:inner"><value>second</value></value></entry>\n</Request>\n',
                    }
                ),
            ),
        ),
        Trait.new(
            id=ShapeID("smithy.test#httpResponseTests"),
            value=(
                MappingProxyType(
                    {
                        "id": "FrozenScopeResponseRenamedPrefixes",
                        "protocol": "aws.protocols#restXml",
                        "code": 200,
                        "params": MappingProxyType(
                            {
                                "nested": MappingProxyType({"value": "inner"}),
                                "after": "outer",
                                "items": (
                                    MappingProxyType({"value": "one"}),
                                    MappingProxyType({"value": "two"}),
                                ),
                                "entries": MappingProxyType(
                                    {
                                        "a": MappingProxyType({"value": "first"}),
                                        "b": MappingProxyType({"value": "second"}),
                                    }
                                ),
                            }
                        ),
                        "bodyMediaType": "application/xml",
                        "body": '<Response xmlns:p="urn:outer">\n  <nested xmlns:q="urn:inner"><value>inner</value></nested>\n  <after>outer</after><unknown><after>ignore</after></unknown>\n  <item xmlns:q="urn:inner"><value>one</value></item>\n  <item xmlns:q="urn:inner"><value>two</value></item>\n  <entry><key>a</key><value xmlns:q="urn:inner"><value>first</value></value></entry>\n  <entry><key>b</key><value xmlns:q="urn:inner"><value>second</value></value></entry>\n</Response>\n',
                    }
                ),
            ),
        ),
        Trait.new(
            id=ShapeID("smithy.api#http"),
            value=MappingProxyType({"method": "POST", "uri": "/exchange", "code": 200}),
        ),
    ],
)

XML_SCOPE = Schema(
    id=ShapeID("cleanroom.restxml#XmlScope"),
    shape_type=ShapeType.SERVICE,
    traits=[
        Trait.new(id=ShapeID("aws.protocols#restXml")),
        Trait.new(
            id=ShapeID("smithy.api#xmlNamespace"),
            value=MappingProxyType({"uri": "urn:outer", "prefix": "o"}),
        ),
    ],
)
