# Code generated by smithy-python-codegen DO NOT EDIT.

from urllib.parse import parse_qsl

from pytest import fail, raises
from smithy_core.aio.retries import SimpleRetryStrategy
from smithy_core.aio.types import AsyncBytesReader
from smithy_core.aio.utils import async_list
from smithy_http import tuples_to_fields
from smithy_http.aio import HTTPResponse as _smithy_http_aio_HTTPResponse
from smithy_http.aio.interfaces import (
    HTTPRequest,
    HTTPResponse as _smithy_http_aio_interfaces_HTTPResponse,
)
from smithy_http.interfaces import HTTPClientConfiguration, HTTPRequestConfiguration
from smithy_test import deep_equal
from smithy_test.xml import xml_equal

from xmlnamespaces.client import Namespaces
from xmlnamespaces.config import Config
from xmlnamespaces.models import (
    DefaultNested,
    DefaultScopeInput,
    DefaultScopeOutput,
    Nested,
    QualifiedInput,
    QualifiedOutput,
    ServiceError,
)


async def test_default_scope_request_request_default_scope() -> None:
    client = Namespaces(
        config=Config(
            endpoint_uri="https://example.com/",
            transport=RequestTestHTTPClient(),
            retry_strategy=SimpleRetryStrategy(max_attempts=1),
        )
    )

    input_ = DefaultScopeInput(
        nested=DefaultNested(value="inner"),
        after="outer",
        items=[DefaultNested(value="one"), DefaultNested(value="two")],
    )

    try:
        await client.default_scope(input_)
        fail("Expected 'TestHttpServiceError' exception to be thrown!")
    except TestHttpServiceError as err:
        actual = err.request

        assert actual.method == "POST"
        assert actual.destination.path == "/default"
        assert actual.destination.host == "example.com"

        query = actual.destination.query
        actual_query_segments: list[str] = query.split("&") if query else []
        expected_query_segments: list[str] = []
        for expected_query_segment in expected_query_segments:
            assert expected_query_segment in actual_query_segments
            actual_query_segments.remove(expected_query_segment)

        actual_query_keys: list[str] = [k.lower() for k, v in parse_qsl(query)]
        forbidden_query_keys: set[str] = set([])
        for forbidden_key in forbidden_query_keys:
            assert forbidden_key.lower() not in actual_query_keys

        required_query_keys: list[str] = []
        for required_query_key in required_query_keys:
            assert required_query_key.lower() in actual_query_keys
            # These are removed because the required list could require more than one
            # value. By removing each value after we assert that it's there, we can
            # effectively validate that without having to have a more complex comparator.
            actual_query_keys.remove(required_query_key)

        expected_headers: list[tuple[str, str]] = []
        for expected_key, expected_val in expected_headers:
            assert expected_val in actual.fields[expected_key].values

        forbidden_headers: set[str] = set([])
        for forbidden_key in forbidden_headers:
            with raises(KeyError):
                actual.fields[forbidden_key]

        required_headers: list[str] = []
        for required_key in required_headers:
            # del Fields[required_key] raises KeyError if key does not exist
            del actual.fields[required_key]

        actual_body_content = await AsyncBytesReader(actual.body or b"").read()
        expected_body_content = b'<DefaultData xmlns="urn:outer"><nested xmlns="urn:inner"><value>inner</value></nested><after>outer</after><items><member xmlns="urn:inner"><value>one</value></member><member xmlns="urn:inner"><value>two</value></member></items></DefaultData>\n'
        assert xml_equal(actual_body_content, expected_body_content)

    except Exception as err:
        fail(
            f"Expected 'TestHttpServiceError' exception to be thrown, but received {type(err).__name__}: {err}"
        )


async def test_default_scope_response_response_default_scope() -> None:
    client = Namespaces(
        config=Config(
            endpoint_uri="https://example.com",
            transport=ResponseTestHTTPClient(
                status=200,
                headers=[],
                body=b'<p:DefaultData xmlns:p="urn:outer" xmlns:q="urn:inner"><q:nested><q:value>inner</q:value></q:nested><p:after>outer</p:after><p:items><q:member><q:value>one</q:value></q:member><q:member><q:value>two</q:value></q:member></p:items></p:DefaultData>\n',
            ),
        )
    )

    input_ = DefaultScopeInput()

    try:
        actual = await client.default_scope(input_)
    except Exception as err:
        fail(f"Expected a valid response, but received: {type(err).__name__}: {err}")
    else:
        expected = DefaultScopeOutput(
            nested=DefaultNested(value="inner"),
            after="outer",
            items=[DefaultNested(value="one"), DefaultNested(value="two")],
        )

        assert deep_equal(actual, expected)


async def test_no_wrapping_failure_error_default_scope() -> None:
    client = Namespaces(
        config=Config(
            endpoint_uri="https://example.com",
            transport=ResponseTestHTTPClient(
                status=409,
                headers=[("x-trace", "trace")],
                body=b'<p:Error xmlns:p="urn:outer" xmlns:q="urn:inner"><p:Code>Failure</p:Code><p:Message>bad</p:Message><q:detail><q:value>inner</q:value></q:detail></p:Error>\n',
            ),
        )
    )

    input_ = DefaultScopeInput()

    try:
        await client.default_scope(input_)
        fail("Expected 'Failure' exception to be thrown!")
    except Exception as err:
        if type(err).__name__ != "Failure":
            fail(
                f"Expected 'Failure' exception to be thrown, but received {type(err).__name__}: {err}"
            )


async def test_qualified_scope_request_request_qualified() -> None:
    client = Namespaces(
        config=Config(
            endpoint_uri="https://example.com/",
            transport=RequestTestHTTPClient(),
            retry_strategy=SimpleRetryStrategy(max_attempts=1),
        )
    )

    input_ = QualifiedInput(
        nested=Nested(value="inner"),
        after="outer",
        items=[Nested(value="one"), Nested(value="two")],
        entries={"a": Nested(value="first"), "b": Nested(value="second")},
        attr='<&"雪',
    )

    try:
        await client.qualified(input_)
        fail("Expected 'TestHttpServiceError' exception to be thrown!")
    except TestHttpServiceError as err:
        actual = err.request

        assert actual.method == "POST"
        assert actual.destination.path == "/qualified"
        assert actual.destination.host == "example.com"

        query = actual.destination.query
        actual_query_segments: list[str] = query.split("&") if query else []
        expected_query_segments: list[str] = []
        for expected_query_segment in expected_query_segments:
            assert expected_query_segment in actual_query_segments
            actual_query_segments.remove(expected_query_segment)

        actual_query_keys: list[str] = [k.lower() for k, v in parse_qsl(query)]
        forbidden_query_keys: set[str] = set([])
        for forbidden_key in forbidden_query_keys:
            assert forbidden_key.lower() not in actual_query_keys

        required_query_keys: list[str] = []
        for required_query_key in required_query_keys:
            assert required_query_key.lower() in actual_query_keys
            # These are removed because the required list could require more than one
            # value. By removing each value after we assert that it's there, we can
            # effectively validate that without having to have a more complex comparator.
            actual_query_keys.remove(required_query_key)

        expected_headers: list[tuple[str, str]] = []
        for expected_key, expected_val in expected_headers:
            assert expected_val in actual.fields[expected_key].values

        forbidden_headers: set[str] = set([])
        for forbidden_key in forbidden_headers:
            with raises(KeyError):
                actual.fields[forbidden_key]

        required_headers: list[str] = []
        for required_key in required_headers:
            # del Fields[required_key] raises KeyError if key does not exist
            del actual.fields[required_key]

        actual_body_content = await AsyncBytesReader(actual.body or b"").read()
        expected_body_content = '<o:Request xmlns="urn:outer" xmlns:o="urn:outer" attr="&lt;&amp;&quot;雪">\n  <o:nested xmlns:o="urn:inner"><o:value>inner</o:value></o:nested>\n  <o:after>outer</o:after>\n  <o:item xmlns:o="urn:inner"><o:value>one</o:value></o:item>\n  <o:item xmlns:o="urn:inner"><o:value>two</o:value></o:item>\n  <o:entry><key>a</key><o:value xmlns:o="urn:inner"><o:value>first</o:value></o:value></o:entry>\n  <o:entry><key>b</key><o:value xmlns:o="urn:inner"><o:value>second</o:value></o:value></o:entry>\n</o:Request>\n'.encode(
            "utf-8"
        )
        assert xml_equal(actual_body_content, expected_body_content)

    except Exception as err:
        fail(
            f"Expected 'TestHttpServiceError' exception to be thrown, but received {type(err).__name__}: {err}"
        )


async def test_qualified_scope_response_response_qualified() -> None:
    client = Namespaces(
        config=Config(
            endpoint_uri="https://example.com",
            transport=ResponseTestHTTPClient(
                status=200,
                headers=[],
                body='<p:Request xmlns="urn:outer" xmlns:p="urn:outer" xmlns:q="urn:inner" attr="&lt;&amp;&quot;雪">\n  <q:nested><q:value>inner</q:value></q:nested><p:after>outer</p:after>\n  <q:item><q:value>one</q:value></q:item><q:item><q:value>two</q:value></q:item>\n  <p:entry><key>a</key><q:value><q:value>first</q:value></q:value></p:entry>\n  <p:entry><key>b</key><q:value><q:value>second</q:value></q:value></p:entry>\n</p:Request>\n'.encode(
                    "utf-8"
                ),
            ),
        )
    )

    input_ = QualifiedInput()

    try:
        actual = await client.qualified(input_)
    except Exception as err:
        fail(f"Expected a valid response, but received: {type(err).__name__}: {err}")
    else:
        expected = QualifiedOutput(
            nested=Nested(value="inner"),
            after="outer",
            items=[Nested(value="one"), Nested(value="two")],
            entries={"a": Nested(value="first"), "b": Nested(value="second")},
            attr='<&"雪',
        )

        assert deep_equal(actual, expected)


async def test_no_wrapping_failure_error_qualified() -> None:
    client = Namespaces(
        config=Config(
            endpoint_uri="https://example.com",
            transport=ResponseTestHTTPClient(
                status=409,
                headers=[("x-trace", "trace")],
                body=b'<p:Error xmlns:p="urn:outer" xmlns:q="urn:inner"><p:Code>Failure</p:Code><p:Message>bad</p:Message><q:detail><q:value>inner</q:value></q:detail></p:Error>\n',
            ),
        )
    )

    input_ = QualifiedInput()

    try:
        await client.qualified(input_)
        fail("Expected 'Failure' exception to be thrown!")
    except Exception as err:
        if type(err).__name__ != "Failure":
            fail(
                f"Expected 'Failure' exception to be thrown, but received {type(err).__name__}: {err}"
            )


class TestHttpServiceError(ServiceError):
    """A test error that subclasses the service-error for protocol tests."""

    def __init__(self, request: HTTPRequest):
        self.request = request


class RequestTestHTTPClient:
    """An asynchronous HTTP client solely for testing purposes."""

    TIMEOUT_EXCEPTIONS = ()
    SUPPORTS_DUPLEX_STREAMING: bool = True

    def __init__(self, *, client_config: HTTPClientConfiguration | None = None):
        self._client_config = client_config

    async def send(
        self,
        request: HTTPRequest,
        *,
        request_config: HTTPRequestConfiguration | None = None,
    ) -> _smithy_http_aio_interfaces_HTTPResponse:
        # Raise the exception with the request object to bypass actual request handling
        raise TestHttpServiceError(request)


class ResponseTestHTTPClient:
    """An asynchronous HTTP client solely for testing purposes."""

    TIMEOUT_EXCEPTIONS = ()
    SUPPORTS_DUPLEX_STREAMING: bool = True

    def __init__(
        self,
        *,
        client_config: HTTPClientConfiguration | None = None,
        status: int = 200,
        headers: list[tuple[str, str]] | None = None,
        body: bytes = b"",
    ):
        self._client_config = client_config
        self.status = status
        self.fields = tuples_to_fields(headers or [])
        self.body = body

    async def send(
        self,
        request: HTTPRequest,
        *,
        request_config: HTTPRequestConfiguration | None = None,
    ) -> _smithy_http_aio_HTTPResponse:
        # Pre-construct the response from the request and return it
        return _smithy_http_aio_HTTPResponse(
            status=self.status, fields=self.fields, body=async_list([self.body])
        )
