# Code generated by smithy-python-codegen DO NOT EDIT.

from dataclasses import dataclass
import logging
from typing import Any, Self

from smithy_core.deserializers import ShapeDeserializer
from smithy_core.documents import TypeRegistry
from smithy_core.exceptions import ModeledError
from smithy_core.schemas import APIOperation, Schema
from smithy_core.serializers import ShapeSerializer
from smithy_core.shapes import ShapeID

from ._private.schemas import (
    INNER as _SCHEMA_INNER,
    PROBE_SCOPE as _SCHEMA_PROBE_SCOPE,
    PROBE_SCOPE_INPUT as _SCHEMA_PROBE_SCOPE_INPUT,
    PROBE_SCOPE_OUTPUT as _SCHEMA_PROBE_SCOPE_OUTPUT,
)


logger = logging.getLogger(__name__)


class ServiceError(ModeledError):
    """
    Base error for all errors in the service.

    Some exceptions do not extend from this class, including
    synthetic, implicit, and shared exception types.
    """


@dataclass(kw_only=True)
class Inner:
    """Dataclass for Inner structure."""

    tag: str | None = None

    value: str | None = None

    def serialize(self, serializer: ShapeSerializer):
        serializer.write_struct(_SCHEMA_INNER, self)

    def serialize_members(self, serializer: ShapeSerializer):
        if self.tag is not None:
            serializer.write_string(_SCHEMA_INNER.members["tag"], self.tag)

        if self.value is not None:
            serializer.write_string(_SCHEMA_INNER.members["value"], self.value)

    @classmethod
    def deserialize(cls, deserializer: ShapeDeserializer) -> Self:
        return cls(**cls.deserialize_kwargs(deserializer))

    @classmethod
    def deserialize_kwargs(cls, deserializer: ShapeDeserializer) -> dict[str, Any]:
        kwargs: dict[str, Any] = {}

        def _consumer(schema: Schema, de: ShapeDeserializer) -> None:
            match schema.expect_member_index():
                case 0:
                    kwargs["tag"] = de.read_string(_SCHEMA_INNER.members["tag"])

                case 1:
                    kwargs["value"] = de.read_string(_SCHEMA_INNER.members["value"])

                case _:
                    logger.debug("Unexpected member schema: %s", schema)

        deserializer.read_struct(_SCHEMA_INNER, consumer=_consumer)
        return kwargs


def _serialize_rows(
    serializer: ShapeSerializer, schema: Schema, value: list[Inner]
) -> None:
    member_schema = schema.members["member"]
    with serializer.begin_list(schema, len(value)) as ls:
        for e in value:
            ls.write_struct(member_schema, e)


def _deserialize_rows(deserializer: ShapeDeserializer, schema: Schema) -> list[Inner]:
    result: list[Inner] = []

    def _read_value(d: ShapeDeserializer):
        if d.is_null():
            d.read_null()

        else:
            result.append(Inner.deserialize(d))

    deserializer.read_list(schema, _read_value)
    return result


@dataclass(kw_only=True)
class ProbeScopeInput:
    """Dataclass for ProbeScopeInput structure."""

    nested: Inner | None = None

    after: str | None = None

    rows: list[Inner] | None = None

    last: str | None = None

    def serialize(self, serializer: ShapeSerializer):
        serializer.write_struct(_SCHEMA_PROBE_SCOPE_INPUT, self)

    def serialize_members(self, serializer: ShapeSerializer):
        if self.nested is not None:
            serializer.write_struct(
                _SCHEMA_PROBE_SCOPE_INPUT.members["nested"], self.nested
            )

        if self.after is not None:
            serializer.write_string(
                _SCHEMA_PROBE_SCOPE_INPUT.members["after"], self.after
            )

        if self.rows is not None:
            _serialize_rows(
                serializer, _SCHEMA_PROBE_SCOPE_INPUT.members["rows"], self.rows
            )

        if self.last is not None:
            serializer.write_string(
                _SCHEMA_PROBE_SCOPE_INPUT.members["last"], self.last
            )

    @classmethod
    def deserialize(cls, deserializer: ShapeDeserializer) -> Self:
        return cls(**cls.deserialize_kwargs(deserializer))

    @classmethod
    def deserialize_kwargs(cls, deserializer: ShapeDeserializer) -> dict[str, Any]:
        kwargs: dict[str, Any] = {}

        def _consumer(schema: Schema, de: ShapeDeserializer) -> None:
            match schema.expect_member_index():
                case 0:
                    kwargs["nested"] = Inner.deserialize(de)

                case 1:
                    kwargs["after"] = de.read_string(
                        _SCHEMA_PROBE_SCOPE_INPUT.members["after"]
                    )

                case 2:
                    kwargs["rows"] = _deserialize_rows(
                        de, _SCHEMA_PROBE_SCOPE_INPUT.members["rows"]
                    )

                case 3:
                    kwargs["last"] = de.read_string(
                        _SCHEMA_PROBE_SCOPE_INPUT.members["last"]
                    )

                case _:
                    logger.debug("Unexpected member schema: %s", schema)

        deserializer.read_struct(_SCHEMA_PROBE_SCOPE_INPUT, consumer=_consumer)
        return kwargs


@dataclass(kw_only=True)
class ProbeScopeOutput:
    """Dataclass for ProbeScopeOutput structure."""

    nested: Inner | None = None

    after: str | None = None

    rows: list[Inner] | None = None

    last: str | None = None

    def serialize(self, serializer: ShapeSerializer):
        serializer.write_struct(_SCHEMA_PROBE_SCOPE_OUTPUT, self)

    def serialize_members(self, serializer: ShapeSerializer):
        if self.nested is not None:
            serializer.write_struct(
                _SCHEMA_PROBE_SCOPE_OUTPUT.members["nested"], self.nested
            )

        if self.after is not None:
            serializer.write_string(
                _SCHEMA_PROBE_SCOPE_OUTPUT.members["after"], self.after
            )

        if self.rows is not None:
            _serialize_rows(
                serializer, _SCHEMA_PROBE_SCOPE_OUTPUT.members["rows"], self.rows
            )

        if self.last is not None:
            serializer.write_string(
                _SCHEMA_PROBE_SCOPE_OUTPUT.members["last"], self.last
            )

    @classmethod
    def deserialize(cls, deserializer: ShapeDeserializer) -> Self:
        return cls(**cls.deserialize_kwargs(deserializer))

    @classmethod
    def deserialize_kwargs(cls, deserializer: ShapeDeserializer) -> dict[str, Any]:
        kwargs: dict[str, Any] = {}

        def _consumer(schema: Schema, de: ShapeDeserializer) -> None:
            match schema.expect_member_index():
                case 0:
                    kwargs["nested"] = Inner.deserialize(de)

                case 1:
                    kwargs["after"] = de.read_string(
                        _SCHEMA_PROBE_SCOPE_OUTPUT.members["after"]
                    )

                case 2:
                    kwargs["rows"] = _deserialize_rows(
                        de, _SCHEMA_PROBE_SCOPE_OUTPUT.members["rows"]
                    )

                case 3:
                    kwargs["last"] = de.read_string(
                        _SCHEMA_PROBE_SCOPE_OUTPUT.members["last"]
                    )

                case _:
                    logger.debug("Unexpected member schema: %s", schema)

        deserializer.read_struct(_SCHEMA_PROBE_SCOPE_OUTPUT, consumer=_consumer)
        return kwargs


PROBE_SCOPE = APIOperation(
    input=ProbeScopeInput,
    output=ProbeScopeOutput,
    schema=_SCHEMA_PROBE_SCOPE,
    input_schema=_SCHEMA_PROBE_SCOPE_INPUT,
    output_schema=_SCHEMA_PROBE_SCOPE_OUTPUT,
    error_registry=TypeRegistry({}),
    effective_auth_schemes=[ShapeID("smithy.api#noAuth")],
    error_schemas=[],
)
