# Code generated by smithy-python-codegen DO NOT EDIT.

from urllib.parse import parse_qsl

from pytest import fail, raises
from smithy_core.aio.retries import SimpleRetryStrategy
from smithy_core.aio.types import AsyncBytesReader
from smithy_core.aio.utils import async_list
from smithy_http import tuples_to_fields
from smithy_http.aio import HTTPResponse as _smithy_http_aio_HTTPResponse
from smithy_http.aio.interfaces import (
    HTTPRequest,
    HTTPResponse as _smithy_http_aio_interfaces_HTTPResponse,
)
from smithy_http.interfaces import HTTPClientConfiguration, HTTPRequestConfiguration
from smithy_test import deep_equal
from smithy_test.xml import xml_equal

from xmlscope.client import XmlScope
from xmlscope.config import Config
from xmlscope.models import ExchangeInput, ExchangeOutput, Nested, ServiceError


async def test_frozen_scope_request_request_exchange() -> None:
    client = XmlScope(
        config=Config(
            endpoint_uri="https://example.com/",
            transport=RequestTestHTTPClient(),
            retry_strategy=SimpleRetryStrategy(max_attempts=1),
        )
    )

    input_ = ExchangeInput(
        nested=Nested(value="inner"),
        after="outer",
        items=[Nested(value="one"), Nested(value="two")],
        entries={"a": Nested(value="first"), "b": Nested(value="second")},
    )

    try:
        await client.exchange(input_)
        fail("Expected 'TestHttpServiceError' exception to be thrown!")
    except TestHttpServiceError as err:
        actual = err.request

        assert actual.method == "POST"
        assert actual.destination.path == "/exchange"
        assert actual.destination.host == "example.com"

        query = actual.destination.query
        actual_query_segments: list[str] = query.split("&") if query else []
        expected_query_segments: list[str] = []
        for expected_query_segment in expected_query_segments:
            assert expected_query_segment in actual_query_segments
            actual_query_segments.remove(expected_query_segment)

        actual_query_keys: list[str] = [k.lower() for k, v in parse_qsl(query)]
        forbidden_query_keys: set[str] = set([])
        for forbidden_key in forbidden_query_keys:
            assert forbidden_key.lower() not in actual_query_keys

        required_query_keys: list[str] = []
        for required_query_key in required_query_keys:
            assert required_query_key.lower() in actual_query_keys
            # These are removed because the required list could require more than one
            # value. By removing each value after we assert that it's there, we can
            # effectively validate that without having to have a more complex comparator.
            actual_query_keys.remove(required_query_key)

        expected_headers: list[tuple[str, str]] = []
        for expected_key, expected_val in expected_headers:
            assert expected_val in actual.fields[expected_key].values

        forbidden_headers: set[str] = set([])
        for forbidden_key in forbidden_headers:
            with raises(KeyError):
                actual.fields[forbidden_key]

        required_headers: list[str] = []
        for required_key in required_headers:
            # del Fields[required_key] raises KeyError if key does not exist
            del actual.fields[required_key]

        actual_body_content = await AsyncBytesReader(actual.body or b"").read()
        expected_body_content = b'<Request xmlns:o="urn:outer">\n  <nested xmlns:o="urn:inner"><value>inner</value></nested>\n  <after>outer</after>\n  <item xmlns:o="urn:inner"><value>one</value></item>\n  <item xmlns:o="urn:inner"><value>two</value></item>\n  <entry><key>a</key><value xmlns:o="urn:inner"><value>first</value></value></entry>\n  <entry><key>b</key><value xmlns:o="urn:inner"><value>second</value></value></entry>\n</Request>\n'
        assert xml_equal(actual_body_content, expected_body_content)

    except Exception as err:
        fail(
            f"Expected 'TestHttpServiceError' exception to be thrown, but received {type(err).__name__}: {err}"
        )


async def test_frozen_scope_response_renamed_prefixes_response_exchange() -> None:
    client = XmlScope(
        config=Config(
            endpoint_uri="https://example.com",
            transport=ResponseTestHTTPClient(
                status=200,
                headers=[],
                body=b'<Response xmlns:p="urn:outer">\n  <nested xmlns:q="urn:inner"><value>inner</value></nested>\n  <after>outer</after><unknown><after>ignore</after></unknown>\n  <item xmlns:q="urn:inner"><value>one</value></item>\n  <item xmlns:q="urn:inner"><value>two</value></item>\n  <entry><key>a</key><value xmlns:q="urn:inner"><value>first</value></value></entry>\n  <entry><key>b</key><value xmlns:q="urn:inner"><value>second</value></value></entry>\n</Response>\n',
            ),
        )
    )

    input_ = ExchangeInput()

    try:
        actual = await client.exchange(input_)
    except Exception as err:
        fail(f"Expected a valid response, but received: {type(err).__name__}: {err}")
    else:
        expected = ExchangeOutput(
            nested=Nested(value="inner"),
            after="outer",
            items=[Nested(value="one"), Nested(value="two")],
            entries={"a": Nested(value="first"), "b": Nested(value="second")},
        )

        assert deep_equal(actual, expected)


async def test_frozen_scope_modeled_failure_error_exchange() -> None:
    client = XmlScope(
        config=Config(
            endpoint_uri="https://example.com",
            transport=ResponseTestHTTPClient(
                status=409,
                headers=[("x-trace", "trace-id")],
                body=b'<ErrorResponse xmlns:q="urn:outer"><Error>\n  <Code>ModeledFailure</Code><Message>bad</Message>\n  <detail xmlns:r="urn:inner"><value>inner</value></detail>\n</Error></ErrorResponse>\n',
            ),
        )
    )

    input_ = ExchangeInput()

    try:
        await client.exchange(input_)
        fail("Expected 'ModeledFailure' exception to be thrown!")
    except Exception as err:
        if type(err).__name__ != "ModeledFailure":
            fail(
                f"Expected 'ModeledFailure' exception to be thrown, but received {type(err).__name__}: {err}"
            )


class TestHttpServiceError(ServiceError):
    """A test error that subclasses the service-error for protocol tests."""

    def __init__(self, request: HTTPRequest):
        self.request = request


class RequestTestHTTPClient:
    """An asynchronous HTTP client solely for testing purposes."""

    TIMEOUT_EXCEPTIONS = ()
    SUPPORTS_DUPLEX_STREAMING: bool = True

    def __init__(self, *, client_config: HTTPClientConfiguration | None = None):
        self._client_config = client_config

    async def send(
        self,
        request: HTTPRequest,
        *,
        request_config: HTTPRequestConfiguration | None = None,
    ) -> _smithy_http_aio_interfaces_HTTPResponse:
        # Raise the exception with the request object to bypass actual request handling
        raise TestHttpServiceError(request)


class ResponseTestHTTPClient:
    """An asynchronous HTTP client solely for testing purposes."""

    TIMEOUT_EXCEPTIONS = ()
    SUPPORTS_DUPLEX_STREAMING: bool = True

    def __init__(
        self,
        *,
        client_config: HTTPClientConfiguration | None = None,
        status: int = 200,
        headers: list[tuple[str, str]] | None = None,
        body: bytes = b"",
    ):
        self._client_config = client_config
        self.status = status
        self.fields = tuples_to_fields(headers or [])
        self.body = body

    async def send(
        self,
        request: HTTPRequest,
        *,
        request_config: HTTPRequestConfiguration | None = None,
    ) -> _smithy_http_aio_HTTPResponse:
        # Pre-construct the response from the request and return it
        return _smithy_http_aio_HTTPResponse(
            status=self.status, fields=self.fields, body=async_list([self.body])
        )
