# Code generated by smithy-python-codegen DO NOT EDIT.

from types import MappingProxyType

from smithy_core.prelude import BLOB, STRING
from smithy_core.schemas import Schema
from smithy_core.shapes import ShapeID, ShapeType
from smithy_core.traits import Trait


BINARY_INPUT = Schema.collection(
    id=ShapeID("cleanroom.regressions#BinaryInput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"),
            value="cleanroom.regressions#BinaryData",
        ),
        Trait.new(id=ShapeID("smithy.api#input")),
    ],
    members={
        "value": {
            "target": BLOB,
            "traits": [Trait.new(id=ShapeID("smithy.api#httpPayload"))],
        }
    },
)

BINARY_OUTPUT = Schema.collection(
    id=ShapeID("cleanroom.regressions#BinaryOutput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"),
            value="cleanroom.regressions#BinaryData",
        ),
        Trait.new(id=ShapeID("smithy.api#output")),
    ],
    members={
        "value": {
            "target": BLOB,
            "traits": [Trait.new(id=ShapeID("smithy.api#httpPayload"))],
        }
    },
)

BINARY = Schema(
    id=ShapeID("cleanroom.regressions#Binary"),
    shape_type=ShapeType.OPERATION,
    traits=[
        Trait.new(
            id=ShapeID("smithy.api#http"),
            value=MappingProxyType({"method": "POST", "uri": "/binary", "code": 200}),
        )
    ],
)

ROOT = Schema.collection(
    id=ShapeID("cleanroom.regressions#Root"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.api#xmlNamespace"),
            value=MappingProxyType({"uri": "urn:target"}),
        )
    ],
    members={"value": {"target": STRING}},
)

CHOICE = Schema.collection(
    id=ShapeID("cleanroom.regressions#Choice"),
    shape_type=ShapeType.UNION,
    members={"text": {"target": STRING}, "nested": {"target": ROOT}},
)

ENTRIES = Schema.collection(
    id=ShapeID("cleanroom.regressions#Entries"),
    shape_type=ShapeType.MAP,
    traits=[
        Trait.new(
            id=ShapeID("smithy.api#xmlNamespace"),
            value=MappingProxyType({"uri": "urn:keys", "prefix": "k"}),
        )
    ],
    members={
        "key": {
            "target": STRING,
            "traits": [Trait.new(id=ShapeID("smithy.api#xmlName"), value="k:key")],
        },
        "value": {
            "target": STRING,
            "traits": [Trait.new(id=ShapeID("smithy.api#xmlName"), value="k:value")],
        },
    },
)

ITEMS = Schema.collection(
    id=ShapeID("cleanroom.regressions#Items"),
    shape_type=ShapeType.LIST,
    members={
        "member": {
            "target": ROOT,
            "traits": [Trait.new(id=ShapeID("smithy.api#xmlName"), value="item")],
        }
    },
)

EXCHANGE_INPUT = Schema.collection(
    id=ShapeID("cleanroom.regressions#ExchangeInput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"),
            value="cleanroom.regressions#Data",
        ),
        Trait.new(id=ShapeID("smithy.api#input")),
    ],
    members={
        "nested": {"target": ROOT},
        "items": {"target": ITEMS},
        "entries": {
            "target": ENTRIES,
            "traits": [
                Trait.new(
                    id=ShapeID("smithy.api#xmlNamespace"),
                    value=MappingProxyType({"uri": "urn:keys", "prefix": "k"}),
                )
            ],
        },
        "choice": {"target": CHOICE},
        "attribute": {
            "target": STRING,
            "traits": [Trait.new(id=ShapeID("smithy.api#xmlAttribute"))],
        },
    },
)

EXCHANGE_OUTPUT = Schema.collection(
    id=ShapeID("cleanroom.regressions#ExchangeOutput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"),
            value="cleanroom.regressions#Data",
        ),
        Trait.new(id=ShapeID("smithy.api#output")),
    ],
    members={
        "nested": {"target": ROOT},
        "items": {"target": ITEMS},
        "entries": {
            "target": ENTRIES,
            "traits": [
                Trait.new(
                    id=ShapeID("smithy.api#xmlNamespace"),
                    value=MappingProxyType({"uri": "urn:keys", "prefix": "k"}),
                )
            ],
        },
        "choice": {"target": CHOICE},
        "attribute": {
            "target": STRING,
            "traits": [Trait.new(id=ShapeID("smithy.api#xmlAttribute"))],
        },
    },
)

FAILURE = Schema.collection(
    id=ShapeID("cleanroom.regressions#Failure"),
    traits=[
        Trait.new(id=ShapeID("smithy.api#error"), value="client"),
        Trait.new(id=ShapeID("smithy.api#httpError"), value=409),
    ],
    members={
        "message": {
            "target": STRING,
            "traits": [Trait.new(id=ShapeID("smithy.api#xmlName"), value="Reason")],
        },
        "detail": {"target": ROOT},
        "trace": {
            "target": STRING,
            "traits": [Trait.new(id=ShapeID("smithy.api#httpHeader"), value="x-trace")],
        },
    },
)

EXCHANGE = Schema(
    id=ShapeID("cleanroom.regressions#Exchange"),
    shape_type=ShapeType.OPERATION,
    traits=[
        Trait.new(
            id=ShapeID("smithy.test#httpRequestTests"),
            value=(
                MappingProxyType(
                    {
                        "id": "NestedTargetNamespaceIgnored",
                        "protocol": "aws.protocols#restXml",
                        "method": "POST",
                        "uri": "/exchange",
                        "params": MappingProxyType(
                            {"nested": MappingProxyType({"value": "inner"})}
                        ),
                        "bodyMediaType": "application/xml",
                        "body": '<Data xmlns="urn:service"><nested><value>inner</value></nested></Data>',
                    }
                ),
            ),
        ),
        Trait.new(
            id=ShapeID("smithy.api#http"),
            value=MappingProxyType({"method": "POST", "uri": "/exchange", "code": 200}),
        ),
    ],
)

PAYLOAD_INPUT = Schema.collection(
    id=ShapeID("cleanroom.regressions#PayloadInput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"),
            value="cleanroom.regressions#PayloadData",
        ),
        Trait.new(id=ShapeID("smithy.api#input")),
    ],
    members={
        "value": {
            "target": ROOT,
            "traits": [Trait.new(id=ShapeID("smithy.api#httpPayload"))],
        }
    },
)

PAYLOAD_OUTPUT = Schema.collection(
    id=ShapeID("cleanroom.regressions#PayloadOutput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"),
            value="cleanroom.regressions#PayloadData",
        ),
        Trait.new(id=ShapeID("smithy.api#output")),
    ],
    members={
        "value": {
            "target": ROOT,
            "traits": [Trait.new(id=ShapeID("smithy.api#httpPayload"))],
        }
    },
)

PAYLOAD = Schema(
    id=ShapeID("cleanroom.regressions#Payload"),
    shape_type=ShapeType.OPERATION,
    traits=[
        Trait.new(
            id=ShapeID("smithy.api#http"),
            value=MappingProxyType({"method": "POST", "uri": "/payload", "code": 200}),
        )
    ],
)

TEXT_INPUT = Schema.collection(
    id=ShapeID("cleanroom.regressions#TextInput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"),
            value="cleanroom.regressions#TextData",
        ),
        Trait.new(id=ShapeID("smithy.api#input")),
    ],
    members={
        "value": {
            "target": STRING,
            "traits": [Trait.new(id=ShapeID("smithy.api#httpPayload"))],
        }
    },
)

TEXT_OUTPUT = Schema.collection(
    id=ShapeID("cleanroom.regressions#TextOutput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"),
            value="cleanroom.regressions#TextData",
        ),
        Trait.new(id=ShapeID("smithy.api#output")),
    ],
    members={
        "value": {
            "target": STRING,
            "traits": [Trait.new(id=ShapeID("smithy.api#httpPayload"))],
        }
    },
)

TEXT = Schema(
    id=ShapeID("cleanroom.regressions#Text"),
    shape_type=ShapeType.OPERATION,
    traits=[
        Trait.new(
            id=ShapeID("smithy.api#http"),
            value=MappingProxyType({"method": "POST", "uri": "/text", "code": 200}),
        )
    ],
)

REGRESSIONS = Schema(
    id=ShapeID("cleanroom.regressions#Regressions"),
    shape_type=ShapeType.SERVICE,
    traits=[
        Trait.new(id=ShapeID("aws.protocols#restXml")),
        Trait.new(
            id=ShapeID("smithy.api#xmlNamespace"),
            value=MappingProxyType({"uri": "urn:service"}),
        ),
    ],
)
