# Code generated by smithy-python-codegen DO NOT EDIT.

from types import MappingProxyType

from smithy_core.prelude import STRING
from smithy_core.schemas import Schema
from smithy_core.shapes import ShapeID, ShapeType
from smithy_core.traits import Trait


INNER = Schema.collection(
    id=ShapeID("parent.scope#Inner"),
    members={
        "tag": {
            "target": STRING,
            "traits": [
                Trait.new(id=ShapeID("smithy.api#xmlName"), value="p:tag"),
                Trait.new(id=ShapeID("smithy.api#xmlAttribute")),
            ],
        },
        "value": {
            "target": STRING,
            "traits": [Trait.new(id=ShapeID("smithy.api#xmlName"), value="p:value")],
        },
    },
)

ROWS = Schema.collection(
    id=ShapeID("parent.scope#Rows"),
    shape_type=ShapeType.LIST,
    members={
        "member": {
            "target": INNER,
            "traits": [
                Trait.new(
                    id=ShapeID("smithy.api#xmlNamespace"),
                    value=MappingProxyType({"uri": "urn:inner", "prefix": "p"}),
                )
            ],
        }
    },
)

PROBE_SCOPE_INPUT = Schema.collection(
    id=ShapeID("parent.scope#ProbeScopeInput"),
    traits=[
        Trait.new(id=ShapeID("smithy.api#xmlName"), value="p:Request"),
        Trait.new(id=ShapeID("smithy.api#input")),
    ],
    members={
        "nested": {
            "target": INNER,
            "traits": [
                Trait.new(id=ShapeID("smithy.api#xmlName"), value="p:nested"),
                Trait.new(
                    id=ShapeID("smithy.api#xmlNamespace"),
                    value=MappingProxyType({"uri": "urn:inner", "prefix": "p"}),
                ),
            ],
        },
        "after": {
            "target": STRING,
            "traits": [Trait.new(id=ShapeID("smithy.api#xmlName"), value="p:after")],
        },
        "rows": {
            "target": ROWS,
            "traits": [
                Trait.new(id=ShapeID("smithy.api#xmlName"), value="p:row"),
                Trait.new(id=ShapeID("smithy.api#xmlFlattened")),
            ],
        },
        "last": {
            "target": STRING,
            "traits": [Trait.new(id=ShapeID("smithy.api#xmlName"), value="p:last")],
        },
    },
)

PROBE_SCOPE_OUTPUT = Schema.collection(
    id=ShapeID("parent.scope#ProbeScopeOutput"),
    traits=[
        Trait.new(id=ShapeID("smithy.api#xmlName"), value="p:Response"),
        Trait.new(id=ShapeID("smithy.api#output")),
    ],
    members={
        "nested": {
            "target": INNER,
            "traits": [
                Trait.new(id=ShapeID("smithy.api#xmlName"), value="p:nested"),
                Trait.new(
                    id=ShapeID("smithy.api#xmlNamespace"),
                    value=MappingProxyType({"uri": "urn:inner", "prefix": "p"}),
                ),
            ],
        },
        "after": {
            "target": STRING,
            "traits": [Trait.new(id=ShapeID("smithy.api#xmlName"), value="p:after")],
        },
        "rows": {
            "target": ROWS,
            "traits": [
                Trait.new(id=ShapeID("smithy.api#xmlName"), value="p:row"),
                Trait.new(id=ShapeID("smithy.api#xmlFlattened")),
            ],
        },
        "last": {
            "target": STRING,
            "traits": [Trait.new(id=ShapeID("smithy.api#xmlName"), value="p:last")],
        },
    },
)

PROBE_SCOPE = Schema(
    id=ShapeID("parent.scope#ProbeScope"),
    shape_type=ShapeType.OPERATION,
    traits=[
        Trait.new(
            id=ShapeID("smithy.test#httpResponseTests"),
            value=(
                MappingProxyType(
                    {
                        "id": "ExplicitNamespaceAfter",
                        "protocol": "aws.protocols#restXml",
                        "code": 200,
                        "params": MappingProxyType({"after": "outside"}),
                        "bodyMediaType": "application/xml",
                        "body": '<a:Response xmlns:a="urn:outer"><a:after>outside</a:after></a:Response>',
                    }
                ),
            ),
        ),
        Trait.new(
            id=ShapeID("smithy.api#http"),
            value=MappingProxyType({"method": "POST", "uri": "/probe", "code": 200}),
        ),
    ],
)

PROBE = Schema(
    id=ShapeID("parent.scope#Probe"),
    shape_type=ShapeType.SERVICE,
    traits=[
        Trait.new(id=ShapeID("aws.protocols#restXml")),
        Trait.new(
            id=ShapeID("smithy.api#xmlNamespace"),
            value=MappingProxyType({"uri": "urn:outer", "prefix": "p"}),
        ),
    ],
)
