# Code generated by smithy-python-codegen DO NOT EDIT.

import asyncio
from copy import deepcopy
import logging
from typing import Any, Self, cast

from smithy_aws_core.config import ConfigSource
from smithy_aws_core.identity import AWSCredentialsIdentity
from smithy_aws_core.identity.chain import IdentityChain
from smithy_core.aio.client import ClientCall, RequestPipeline
from smithy_core.aio.retries import RetryStrategyResolver
from smithy_core.aio.utils import close
from smithy_core.exceptions import ExpectationNotMetError
from smithy_core.interceptors import InterceptorChain
from smithy_core.types import TypedProperties
from smithy_http.aio.interfaces import HTTPClient
from smithy_http.plugins import user_agent_plugin

from .config import AsyncJSONRPC10Config, Plugin
from .models import (
    CONTENT_TYPE_PARAMETERS,
    ClientOptionalDefaults,
    ContentTypeParametersInput,
    ContentTypeParametersOutput,
    Defaults,
    EMPTY_INPUT_AND_EMPTY_OUTPUT,
    ENDPOINT_OPERATION,
    ENDPOINT_WITH_HOST_LABEL_OPERATION,
    EmptyInputAndEmptyOutputInput,
    EmptyInputAndEmptyOutputOutput,
    EndpointOperationInput,
    EndpointOperationOutput,
    EndpointWithHostLabelOperationInput,
    EndpointWithHostLabelOperationOutput,
    GREETING_WITH_ERRORS,
    GreetingWithErrorsInput,
    GreetingWithErrorsOutput,
    HOST_WITH_PATH_OPERATION,
    HostWithPathOperationInput,
    HostWithPathOperationOutput,
    JSON_UNIONS,
    JsonUnionsInput,
    JsonUnionsOutput,
    MyUnion,
    NO_INPUT_AND_NO_OUTPUT,
    NO_INPUT_AND_OUTPUT,
    NoInputAndNoOutputInput,
    NoInputAndNoOutputOutput,
    NoInputAndOutputInput,
    NoInputAndOutputOutput,
    OPERATION_WITH_DEFAULTS,
    OPERATION_WITH_NESTED_STRUCTURE,
    OPERATION_WITH_REQUIRED_MEMBERS,
    OPERATION_WITH_REQUIRED_MEMBERS_WITH_DEFAULTS,
    OperationWithDefaultsInput,
    OperationWithDefaultsOutput,
    OperationWithNestedStructureInput,
    OperationWithNestedStructureOutput,
    OperationWithRequiredMembersInput,
    OperationWithRequiredMembersOutput,
    OperationWithRequiredMembersWithDefaultsInput,
    OperationWithRequiredMembersWithDefaultsOutput,
    PUT_WITH_CONTENT_ENCODING,
    PutWithContentEncodingInput,
    PutWithContentEncodingOutput,
    QUERY_INCOMPATIBLE_OPERATION,
    QueryIncompatibleOperationInput,
    QueryIncompatibleOperationOutput,
    SIMPLE_SCALAR_PROPERTIES,
    SimpleScalarPropertiesInput,
    SimpleScalarPropertiesOutput,
    TopLevel,
)
from .user_agent import aws_user_agent_plugin


logger = logging.getLogger(__name__)


class AsyncJSONRPC10Client:
    """Client for JsonRpc10"""

    def __init__(
        self,
        config: AsyncJSONRPC10Config | None = None,
        plugins: list[Plugin] | None = None,
    ):
        """
        Constructor for `AsyncJSONRPC10Client`.

        Args:
            config:
                Optional configuration for the client. Here you can set things like
                the endpoint for HTTP services or auth credentials.
            plugins:
                A list of callables applied once to the client's base configuration.
                Their changes are inherited by every operation invocation.
        """
        self._config = config
        self._plugins = plugins
        self._derive_lock = asyncio.Lock()
        self._setup_done = False
        self._closed = False
        self._retry_strategy_resolver = RetryStrategyResolver()
        self._client_plugins: list[Plugin] = [aws_user_agent_plugin, user_agent_plugin]

    async def _ensure_setup(self) -> None:
        if not self._setup_done:
            async with self._derive_lock:
                if not self._setup_done:
                    if self._config is None:
                        config = await AsyncJSONRPC10Config.resolve()
                    else:
                        # Copy so plugins don't mutate the caller's config.
                        config = deepcopy(self._config)
                    for plugin in self._client_plugins:
                        plugin(config)
                    if self._plugins:
                        for plugin in self._plugins:
                            plugin(config)
                    self._config = config

                    if self._config.aws_credentials_identity_resolver is None:
                        config_context = self._config.resolution_context()
                        config_file = None
                        profile_name = None
                        if config_context is not None:
                            config_file = await config_context.parsed_profiles()
                            if config_context.profile_source is ConfigSource.OVERRIDE:
                                profile_name = config_context.profile_name
                        self._config.aws_credentials_identity_resolver = (
                            await IdentityChain.create(
                                AWSCredentialsIdentity,
                                config_file=config_file,
                                profile_name=profile_name,
                                region_override=self._config.region,
                                http_client=cast(
                                    HTTPClient | None, self._config.transport
                                ),
                            )
                        )
                    self._setup_done = True

    async def close(self) -> None:
        """Close this client and any resources held by its transport."""
        if self._closed:
            return
        async with self._derive_lock:
            if self._closed:
                return
            self._closed = True
            if self._setup_done and self._config is not None:
                await close(self._config.transport)

    async def __aenter__(self) -> Self:
        if self._closed:
            raise RuntimeError("Cannot enter a client that has been closed.")
        return self

    async def __aexit__(self, exc_type: Any, exc_value: Any, traceback: Any) -> None:
        await self.close()

    async def content_type_parameters(
        self, *, value: int | None = None, plugins: list[Plugin] | None = None
    ) -> ContentTypeParametersOutput:
        """
        The example tests how servers must support requests containing a
        `Content-Type` header with parameters.

        Args:
            value:
                The `value` input member.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `ContentTypeParametersOutput`.
        """
        input = ContentTypeParametersInput(value=value)
        if self._closed:
            raise RuntimeError(
                "Cannot invoke an operation on a client that has been closed."
            )

        operation_plugins: list[Plugin] = []
        if plugins:
            operation_plugins.extend(plugins)
        await self._ensure_setup()
        assert self._config is not None
        if operation_plugins:
            # Keep operation-plugin mutations scoped to this call.
            config = deepcopy(self._config)
            for plugin in operation_plugins:
                plugin(config)
        else:
            config = self._config
        if (
            config.protocol is None
            or config.transport is None
            or config.endpoint_resolver is None
            or config.auth_scheme_resolver is None
            or config.auth_schemes is None
        ):
            raise ExpectationNotMetError(
                "protocol, transport, endpoint_resolver, auth_scheme_resolver,"
                " and auth_schemes MUST be set on the config to make calls."
            )

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy,
            retry_mode=config.retry_mode,
            max_attempts=config.max_attempts,
        )

        pipeline = RequestPipeline(protocol=config.protocol, transport=config.transport)
        call = ClientCall(
            input=input,
            operation=CONTENT_TYPE_PARAMETERS,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline(call)

    async def empty_input_and_empty_output(
        self, *, plugins: list[Plugin] | None = None
    ) -> EmptyInputAndEmptyOutputOutput:
        """
        The example tests how requests and responses are serialized when
        there's no request or response payload because the operation has an
        empty input and empty output structure that reuses the same shape. While
        this should be rare, code generators must support this.

        Args:

            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `EmptyInputAndEmptyOutputOutput`.
        """
        input = EmptyInputAndEmptyOutputInput()
        if self._closed:
            raise RuntimeError(
                "Cannot invoke an operation on a client that has been closed."
            )

        operation_plugins: list[Plugin] = []
        if plugins:
            operation_plugins.extend(plugins)
        await self._ensure_setup()
        assert self._config is not None
        if operation_plugins:
            # Keep operation-plugin mutations scoped to this call.
            config = deepcopy(self._config)
            for plugin in operation_plugins:
                plugin(config)
        else:
            config = self._config
        if (
            config.protocol is None
            or config.transport is None
            or config.endpoint_resolver is None
            or config.auth_scheme_resolver is None
            or config.auth_schemes is None
        ):
            raise ExpectationNotMetError(
                "protocol, transport, endpoint_resolver, auth_scheme_resolver,"
                " and auth_schemes MUST be set on the config to make calls."
            )

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy,
            retry_mode=config.retry_mode,
            max_attempts=config.max_attempts,
        )

        pipeline = RequestPipeline(protocol=config.protocol, transport=config.transport)
        call = ClientCall(
            input=input,
            operation=EMPTY_INPUT_AND_EMPTY_OUTPUT,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline(call)

    async def endpoint_operation(
        self, *, plugins: list[Plugin] | None = None
    ) -> EndpointOperationOutput:
        """
        Invokes the EndpointOperation operation.

        Args:

            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `EndpointOperationOutput`.
        """
        input = EndpointOperationInput()
        if self._closed:
            raise RuntimeError(
                "Cannot invoke an operation on a client that has been closed."
            )

        operation_plugins: list[Plugin] = []
        if plugins:
            operation_plugins.extend(plugins)
        await self._ensure_setup()
        assert self._config is not None
        if operation_plugins:
            # Keep operation-plugin mutations scoped to this call.
            config = deepcopy(self._config)
            for plugin in operation_plugins:
                plugin(config)
        else:
            config = self._config
        if (
            config.protocol is None
            or config.transport is None
            or config.endpoint_resolver is None
            or config.auth_scheme_resolver is None
            or config.auth_schemes is None
        ):
            raise ExpectationNotMetError(
                "protocol, transport, endpoint_resolver, auth_scheme_resolver,"
                " and auth_schemes MUST be set on the config to make calls."
            )

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy,
            retry_mode=config.retry_mode,
            max_attempts=config.max_attempts,
        )

        pipeline = RequestPipeline(protocol=config.protocol, transport=config.transport)
        call = ClientCall(
            input=input,
            operation=ENDPOINT_OPERATION,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline(call)

    async def endpoint_with_host_label_operation(
        self, *, label: str | None = None, plugins: list[Plugin] | None = None
    ) -> EndpointWithHostLabelOperationOutput:
        """
        Invokes the EndpointWithHostLabelOperation operation.

        Args:
            label:
                The `label` input member.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `EndpointWithHostLabelOperationOutput`.
        """
        input = EndpointWithHostLabelOperationInput(label=label)
        if self._closed:
            raise RuntimeError(
                "Cannot invoke an operation on a client that has been closed."
            )

        operation_plugins: list[Plugin] = []
        if plugins:
            operation_plugins.extend(plugins)
        await self._ensure_setup()
        assert self._config is not None
        if operation_plugins:
            # Keep operation-plugin mutations scoped to this call.
            config = deepcopy(self._config)
            for plugin in operation_plugins:
                plugin(config)
        else:
            config = self._config
        if (
            config.protocol is None
            or config.transport is None
            or config.endpoint_resolver is None
            or config.auth_scheme_resolver is None
            or config.auth_schemes is None
        ):
            raise ExpectationNotMetError(
                "protocol, transport, endpoint_resolver, auth_scheme_resolver,"
                " and auth_schemes MUST be set on the config to make calls."
            )

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy,
            retry_mode=config.retry_mode,
            max_attempts=config.max_attempts,
        )

        pipeline = RequestPipeline(protocol=config.protocol, transport=config.transport)
        call = ClientCall(
            input=input,
            operation=ENDPOINT_WITH_HOST_LABEL_OPERATION,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline(call)

    async def greeting_with_errors(
        self, *, greeting: str | None = None, plugins: list[Plugin] | None = None
    ) -> GreetingWithErrorsOutput:
        """
        This operation has three possible return values: 1. A successful
        response in the form of GreetingWithErrorsOutput 2. An InvalidGreeting
        error. 3. A ComplexError error. Implementations must be able to
        successfully take a response and properly deserialize successful and
        error responses.

        Args:
            greeting:
                The `greeting` input member.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `GreetingWithErrorsOutput`.
        """
        input = GreetingWithErrorsInput(greeting=greeting)
        if self._closed:
            raise RuntimeError(
                "Cannot invoke an operation on a client that has been closed."
            )

        operation_plugins: list[Plugin] = []
        if plugins:
            operation_plugins.extend(plugins)
        await self._ensure_setup()
        assert self._config is not None
        if operation_plugins:
            # Keep operation-plugin mutations scoped to this call.
            config = deepcopy(self._config)
            for plugin in operation_plugins:
                plugin(config)
        else:
            config = self._config
        if (
            config.protocol is None
            or config.transport is None
            or config.endpoint_resolver is None
            or config.auth_scheme_resolver is None
            or config.auth_schemes is None
        ):
            raise ExpectationNotMetError(
                "protocol, transport, endpoint_resolver, auth_scheme_resolver,"
                " and auth_schemes MUST be set on the config to make calls."
            )

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy,
            retry_mode=config.retry_mode,
            max_attempts=config.max_attempts,
        )

        pipeline = RequestPipeline(protocol=config.protocol, transport=config.transport)
        call = ClientCall(
            input=input,
            operation=GREETING_WITH_ERRORS,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline(call)

    async def host_with_path_operation(
        self, *, plugins: list[Plugin] | None = None
    ) -> HostWithPathOperationOutput:
        """
        Invokes the HostWithPathOperation operation.

        Args:

            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `HostWithPathOperationOutput`.
        """
        input = HostWithPathOperationInput()
        if self._closed:
            raise RuntimeError(
                "Cannot invoke an operation on a client that has been closed."
            )

        operation_plugins: list[Plugin] = []
        if plugins:
            operation_plugins.extend(plugins)
        await self._ensure_setup()
        assert self._config is not None
        if operation_plugins:
            # Keep operation-plugin mutations scoped to this call.
            config = deepcopy(self._config)
            for plugin in operation_plugins:
                plugin(config)
        else:
            config = self._config
        if (
            config.protocol is None
            or config.transport is None
            or config.endpoint_resolver is None
            or config.auth_scheme_resolver is None
            or config.auth_schemes is None
        ):
            raise ExpectationNotMetError(
                "protocol, transport, endpoint_resolver, auth_scheme_resolver,"
                " and auth_schemes MUST be set on the config to make calls."
            )

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy,
            retry_mode=config.retry_mode,
            max_attempts=config.max_attempts,
        )

        pipeline = RequestPipeline(protocol=config.protocol, transport=config.transport)
        call = ClientCall(
            input=input,
            operation=HOST_WITH_PATH_OPERATION,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline(call)

    async def json_unions(
        self, *, contents: MyUnion | None = None, plugins: list[Plugin] | None = None
    ) -> JsonUnionsOutput:
        """
        This operation uses unions for inputs and outputs.

        Args:
            contents:
                A union with a representative set of types for members.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `JsonUnionsOutput`.
        """
        input = JsonUnionsInput(contents=contents)
        if self._closed:
            raise RuntimeError(
                "Cannot invoke an operation on a client that has been closed."
            )

        operation_plugins: list[Plugin] = []
        if plugins:
            operation_plugins.extend(plugins)
        await self._ensure_setup()
        assert self._config is not None
        if operation_plugins:
            # Keep operation-plugin mutations scoped to this call.
            config = deepcopy(self._config)
            for plugin in operation_plugins:
                plugin(config)
        else:
            config = self._config
        if (
            config.protocol is None
            or config.transport is None
            or config.endpoint_resolver is None
            or config.auth_scheme_resolver is None
            or config.auth_schemes is None
        ):
            raise ExpectationNotMetError(
                "protocol, transport, endpoint_resolver, auth_scheme_resolver,"
                " and auth_schemes MUST be set on the config to make calls."
            )

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy,
            retry_mode=config.retry_mode,
            max_attempts=config.max_attempts,
        )

        pipeline = RequestPipeline(protocol=config.protocol, transport=config.transport)
        call = ClientCall(
            input=input,
            operation=JSON_UNIONS,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline(call)

    async def no_input_and_no_output(
        self, *, plugins: list[Plugin] | None = None
    ) -> NoInputAndNoOutputOutput:
        """
        The example tests how requests and responses are serialized when
        there's no request or response payload because the operation has no
        input or output. While this should be rare, code generators must support
        this.

        Args:

            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `NoInputAndNoOutputOutput`.
        """
        input = NoInputAndNoOutputInput()
        if self._closed:
            raise RuntimeError(
                "Cannot invoke an operation on a client that has been closed."
            )

        operation_plugins: list[Plugin] = []
        if plugins:
            operation_plugins.extend(plugins)
        await self._ensure_setup()
        assert self._config is not None
        if operation_plugins:
            # Keep operation-plugin mutations scoped to this call.
            config = deepcopy(self._config)
            for plugin in operation_plugins:
                plugin(config)
        else:
            config = self._config
        if (
            config.protocol is None
            or config.transport is None
            or config.endpoint_resolver is None
            or config.auth_scheme_resolver is None
            or config.auth_schemes is None
        ):
            raise ExpectationNotMetError(
                "protocol, transport, endpoint_resolver, auth_scheme_resolver,"
                " and auth_schemes MUST be set on the config to make calls."
            )

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy,
            retry_mode=config.retry_mode,
            max_attempts=config.max_attempts,
        )

        pipeline = RequestPipeline(protocol=config.protocol, transport=config.transport)
        call = ClientCall(
            input=input,
            operation=NO_INPUT_AND_NO_OUTPUT,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline(call)

    async def no_input_and_output(
        self, *, plugins: list[Plugin] | None = None
    ) -> NoInputAndOutputOutput:
        """
        The example tests how requests and responses are serialized when
        there's no request or response payload because the operation has no
        input and the output is empty. While this should be rare, code
        generators must support this.

        Args:

            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `NoInputAndOutputOutput`.
        """
        input = NoInputAndOutputInput()
        if self._closed:
            raise RuntimeError(
                "Cannot invoke an operation on a client that has been closed."
            )

        operation_plugins: list[Plugin] = []
        if plugins:
            operation_plugins.extend(plugins)
        await self._ensure_setup()
        assert self._config is not None
        if operation_plugins:
            # Keep operation-plugin mutations scoped to this call.
            config = deepcopy(self._config)
            for plugin in operation_plugins:
                plugin(config)
        else:
            config = self._config
        if (
            config.protocol is None
            or config.transport is None
            or config.endpoint_resolver is None
            or config.auth_scheme_resolver is None
            or config.auth_schemes is None
        ):
            raise ExpectationNotMetError(
                "protocol, transport, endpoint_resolver, auth_scheme_resolver,"
                " and auth_schemes MUST be set on the config to make calls."
            )

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy,
            retry_mode=config.retry_mode,
            max_attempts=config.max_attempts,
        )

        pipeline = RequestPipeline(protocol=config.protocol, transport=config.transport)
        call = ClientCall(
            input=input,
            operation=NO_INPUT_AND_OUTPUT,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline(call)

    async def operation_with_defaults(
        self,
        *,
        defaults: Defaults | None = None,
        client_optional_defaults: ClientOptionalDefaults | None = None,
        top_level_default: str = "hi",
        other_top_level_default: int = 0,
        plugins: list[Plugin] | None = None,
    ) -> OperationWithDefaultsOutput:
        """
        Invokes the OperationWithDefaults operation.

        Args:
            defaults:
                The `defaults` input member.
            client_optional_defaults:
                The `client_optional_defaults` input member.
            top_level_default:
                The `top_level_default` input member.
            other_top_level_default:
                The `other_top_level_default` input member.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `OperationWithDefaultsOutput`.
        """
        input = OperationWithDefaultsInput(
            defaults=defaults,
            client_optional_defaults=client_optional_defaults,
            top_level_default=top_level_default,
            other_top_level_default=other_top_level_default,
        )
        if self._closed:
            raise RuntimeError(
                "Cannot invoke an operation on a client that has been closed."
            )

        operation_plugins: list[Plugin] = []
        if plugins:
            operation_plugins.extend(plugins)
        await self._ensure_setup()
        assert self._config is not None
        if operation_plugins:
            # Keep operation-plugin mutations scoped to this call.
            config = deepcopy(self._config)
            for plugin in operation_plugins:
                plugin(config)
        else:
            config = self._config
        if (
            config.protocol is None
            or config.transport is None
            or config.endpoint_resolver is None
            or config.auth_scheme_resolver is None
            or config.auth_schemes is None
        ):
            raise ExpectationNotMetError(
                "protocol, transport, endpoint_resolver, auth_scheme_resolver,"
                " and auth_schemes MUST be set on the config to make calls."
            )

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy,
            retry_mode=config.retry_mode,
            max_attempts=config.max_attempts,
        )

        pipeline = RequestPipeline(protocol=config.protocol, transport=config.transport)
        call = ClientCall(
            input=input,
            operation=OPERATION_WITH_DEFAULTS,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline(call)

    async def operation_with_nested_structure(
        self, *, top_level: TopLevel | None = None, plugins: list[Plugin] | None = None
    ) -> OperationWithNestedStructureOutput:
        """
        Invokes the OperationWithNestedStructure operation.

        Args:
            top_level:
                The `top_level` input member.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `OperationWithNestedStructureOutput`.
        """
        input = OperationWithNestedStructureInput(top_level=top_level)
        if self._closed:
            raise RuntimeError(
                "Cannot invoke an operation on a client that has been closed."
            )

        operation_plugins: list[Plugin] = []
        if plugins:
            operation_plugins.extend(plugins)
        await self._ensure_setup()
        assert self._config is not None
        if operation_plugins:
            # Keep operation-plugin mutations scoped to this call.
            config = deepcopy(self._config)
            for plugin in operation_plugins:
                plugin(config)
        else:
            config = self._config
        if (
            config.protocol is None
            or config.transport is None
            or config.endpoint_resolver is None
            or config.auth_scheme_resolver is None
            or config.auth_schemes is None
        ):
            raise ExpectationNotMetError(
                "protocol, transport, endpoint_resolver, auth_scheme_resolver,"
                " and auth_schemes MUST be set on the config to make calls."
            )

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy,
            retry_mode=config.retry_mode,
            max_attempts=config.max_attempts,
        )

        pipeline = RequestPipeline(protocol=config.protocol, transport=config.transport)
        call = ClientCall(
            input=input,
            operation=OPERATION_WITH_NESTED_STRUCTURE,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline(call)

    async def operation_with_required_members(
        self, *, plugins: list[Plugin] | None = None
    ) -> OperationWithRequiredMembersOutput:
        """
        Invokes the OperationWithRequiredMembers operation.

        Args:

            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `OperationWithRequiredMembersOutput`.
        """
        input = OperationWithRequiredMembersInput()
        if self._closed:
            raise RuntimeError(
                "Cannot invoke an operation on a client that has been closed."
            )

        operation_plugins: list[Plugin] = []
        if plugins:
            operation_plugins.extend(plugins)
        await self._ensure_setup()
        assert self._config is not None
        if operation_plugins:
            # Keep operation-plugin mutations scoped to this call.
            config = deepcopy(self._config)
            for plugin in operation_plugins:
                plugin(config)
        else:
            config = self._config
        if (
            config.protocol is None
            or config.transport is None
            or config.endpoint_resolver is None
            or config.auth_scheme_resolver is None
            or config.auth_schemes is None
        ):
            raise ExpectationNotMetError(
                "protocol, transport, endpoint_resolver, auth_scheme_resolver,"
                " and auth_schemes MUST be set on the config to make calls."
            )

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy,
            retry_mode=config.retry_mode,
            max_attempts=config.max_attempts,
        )

        pipeline = RequestPipeline(protocol=config.protocol, transport=config.transport)
        call = ClientCall(
            input=input,
            operation=OPERATION_WITH_REQUIRED_MEMBERS,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline(call)

    async def operation_with_required_members_with_defaults(
        self, *, plugins: list[Plugin] | None = None
    ) -> OperationWithRequiredMembersWithDefaultsOutput:
        """
        Invokes the OperationWithRequiredMembersWithDefaults operation.

        Args:

            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `OperationWithRequiredMembersWithDefaultsOutput`.
        """
        input = OperationWithRequiredMembersWithDefaultsInput()
        if self._closed:
            raise RuntimeError(
                "Cannot invoke an operation on a client that has been closed."
            )

        operation_plugins: list[Plugin] = []
        if plugins:
            operation_plugins.extend(plugins)
        await self._ensure_setup()
        assert self._config is not None
        if operation_plugins:
            # Keep operation-plugin mutations scoped to this call.
            config = deepcopy(self._config)
            for plugin in operation_plugins:
                plugin(config)
        else:
            config = self._config
        if (
            config.protocol is None
            or config.transport is None
            or config.endpoint_resolver is None
            or config.auth_scheme_resolver is None
            or config.auth_schemes is None
        ):
            raise ExpectationNotMetError(
                "protocol, transport, endpoint_resolver, auth_scheme_resolver,"
                " and auth_schemes MUST be set on the config to make calls."
            )

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy,
            retry_mode=config.retry_mode,
            max_attempts=config.max_attempts,
        )

        pipeline = RequestPipeline(protocol=config.protocol, transport=config.transport)
        call = ClientCall(
            input=input,
            operation=OPERATION_WITH_REQUIRED_MEMBERS_WITH_DEFAULTS,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline(call)

    async def put_with_content_encoding(
        self,
        *,
        encoding: str | None = None,
        data: str | None = None,
        plugins: list[Plugin] | None = None,
    ) -> PutWithContentEncodingOutput:
        """
        Invokes the PutWithContentEncoding operation.

        Args:
            encoding:
                The `encoding` input member.
            data:
                The `data` input member.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `PutWithContentEncodingOutput`.
        """
        input = PutWithContentEncodingInput(encoding=encoding, data=data)
        if self._closed:
            raise RuntimeError(
                "Cannot invoke an operation on a client that has been closed."
            )

        operation_plugins: list[Plugin] = []
        if plugins:
            operation_plugins.extend(plugins)
        await self._ensure_setup()
        assert self._config is not None
        if operation_plugins:
            # Keep operation-plugin mutations scoped to this call.
            config = deepcopy(self._config)
            for plugin in operation_plugins:
                plugin(config)
        else:
            config = self._config
        if (
            config.protocol is None
            or config.transport is None
            or config.endpoint_resolver is None
            or config.auth_scheme_resolver is None
            or config.auth_schemes is None
        ):
            raise ExpectationNotMetError(
                "protocol, transport, endpoint_resolver, auth_scheme_resolver,"
                " and auth_schemes MUST be set on the config to make calls."
            )

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy,
            retry_mode=config.retry_mode,
            max_attempts=config.max_attempts,
        )

        pipeline = RequestPipeline(protocol=config.protocol, transport=config.transport)
        call = ClientCall(
            input=input,
            operation=PUT_WITH_CONTENT_ENCODING,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline(call)

    async def query_incompatible_operation(
        self, *, plugins: list[Plugin] | None = None
    ) -> QueryIncompatibleOperationOutput:
        """
        Invokes the QueryIncompatibleOperation operation.

        Args:

            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `QueryIncompatibleOperationOutput`.
        """
        input = QueryIncompatibleOperationInput()
        if self._closed:
            raise RuntimeError(
                "Cannot invoke an operation on a client that has been closed."
            )

        operation_plugins: list[Plugin] = []
        if plugins:
            operation_plugins.extend(plugins)
        await self._ensure_setup()
        assert self._config is not None
        if operation_plugins:
            # Keep operation-plugin mutations scoped to this call.
            config = deepcopy(self._config)
            for plugin in operation_plugins:
                plugin(config)
        else:
            config = self._config
        if (
            config.protocol is None
            or config.transport is None
            or config.endpoint_resolver is None
            or config.auth_scheme_resolver is None
            or config.auth_schemes is None
        ):
            raise ExpectationNotMetError(
                "protocol, transport, endpoint_resolver, auth_scheme_resolver,"
                " and auth_schemes MUST be set on the config to make calls."
            )

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy,
            retry_mode=config.retry_mode,
            max_attempts=config.max_attempts,
        )

        pipeline = RequestPipeline(protocol=config.protocol, transport=config.transport)
        call = ClientCall(
            input=input,
            operation=QUERY_INCOMPATIBLE_OPERATION,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline(call)

    async def simple_scalar_properties(
        self,
        *,
        float_value: float | None = None,
        double_value: float | None = None,
        plugins: list[Plugin] | None = None,
    ) -> SimpleScalarPropertiesOutput:
        """
        Invokes the SimpleScalarProperties operation.

        Args:
            float_value:
                The `float_value` input member.
            double_value:
                The `double_value` input member.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `SimpleScalarPropertiesOutput`.
        """
        input = SimpleScalarPropertiesInput(
            float_value=float_value, double_value=double_value
        )
        if self._closed:
            raise RuntimeError(
                "Cannot invoke an operation on a client that has been closed."
            )

        operation_plugins: list[Plugin] = []
        if plugins:
            operation_plugins.extend(plugins)
        await self._ensure_setup()
        assert self._config is not None
        if operation_plugins:
            # Keep operation-plugin mutations scoped to this call.
            config = deepcopy(self._config)
            for plugin in operation_plugins:
                plugin(config)
        else:
            config = self._config
        if (
            config.protocol is None
            or config.transport is None
            or config.endpoint_resolver is None
            or config.auth_scheme_resolver is None
            or config.auth_schemes is None
        ):
            raise ExpectationNotMetError(
                "protocol, transport, endpoint_resolver, auth_scheme_resolver,"
                " and auth_schemes MUST be set on the config to make calls."
            )

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy,
            retry_mode=config.retry_mode,
            max_attempts=config.max_attempts,
        )

        pipeline = RequestPipeline(protocol=config.protocol, transport=config.transport)
        call = ClientCall(
            input=input,
            operation=SIMPLE_SCALAR_PROPERTIES,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline(call)
